! Generated by xj2f.py 0.1.0 from american_options.ijs
module american_options_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: american_price, price_strikes, spot, rate, volatility, maturity, steps
  integer :: spot, maturity, steps
  real(kind=dp) :: rate, volatility

contains

! y is one strike. Return the American call price and put price.
! J: american_price =: 3 : 0
pure function american_price(y) result(j_result)
  integer, intent(in) :: y
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp) :: dt, up, down, probability_up, probability_down, discount
  real(kind=dp), allocatable :: terminal_stock(:), call_values(:), put_values(:), call_down(:), &
     & call_up(:), put_down(:), put_up(:), call_continuation(:), put_continuation(:), node_stock(: &
     & ), call_exercise(:), put_exercise(:)
  integer :: iteration, step
  dt = real(maturity, kind=dp) / steps
  up = exp(volatility * sqrt(dt))
  down = 1.0_dp / up
  probability_up = (exp(rate * dt) - down) / (up - down)
  probability_down = 1 - probability_up
  discount = exp(-(rate * dt))
  ! At expiry, node j has j upward and steps-j downward moves.
  ! J: terminal_stock =. spot * up ^ (2 * i. 1 + steps) - steps
  terminal_stock = spot * up**(2 * j_iota(1 + steps) - steps)
  call_values = max(0.0_dp, terminal_stock - y)
  put_values = max(0.0_dp, y - terminal_stock)
  ! Work backward, comparing continuation value with immediate exercise.
  ! J: for_iteration. i. steps do.
  do iteration = 0, steps - 1
    step = steps - 1 - iteration
    call_down = call_values(:size(call_values) - 1)
    call_up = call_values(2:)
    put_down = put_values(:size(put_values) - 1)
    put_up = put_values(2:)
    call_continuation = discount * (probability_down * call_down + probability_up * call_up)
    put_continuation = discount * (probability_down * put_down + probability_up * put_up)
    node_stock = spot * up**(2 * j_iota(1 + step) - step)
    call_exercise = max(0.0_dp, node_stock - y)
    put_exercise = max(0.0_dp, y - node_stock)
    call_values = max(call_exercise, call_continuation)
    put_values = max(put_exercise, put_continuation)
  end do
  j_result = [real(kind=dp) :: call_values, put_values]
end function american_price

pure function price_strikes(y) result(j_result)
  integer, intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:,:)
  real(kind=dp), allocatable :: call_results(:), put_results(:), option_prices(:)
  integer :: index
  call_results = reshape([0.0_dp], [0])
  put_results = reshape([0.0_dp], [0])
  do index = 0, size(y, 1) - 1
    option_prices = american_price(y(index + 1))
    call_results = [real(kind=dp) :: call_results, option_prices(1)]
    put_results = [real(kind=dp) :: put_results, option_prices(2)]
  end do
  j_result = reshape([call_results, put_results], [2, size(call_results)], order=[2, 1])
end function price_strikes

pure function j_iota(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:)
  integer :: value_index
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n))
  do value_index = 1, n
    values(value_index) = value_index - 1
  end do
end function j_iota

end module american_options_j_mod

program american_options_j
  use american_options_j_mod, only: american_price, maturity, price_strikes, rate, spot, steps, &
     & volatility
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer, allocatable :: strikes(:)
  real(kind=dp), allocatable :: prices(:,:)
  ! Price American call and put options with a Cox-Ross-Rubinstein tree.
  ! J: spot =: 100
  spot = 100
  rate = 0.05_dp
  volatility = 0.2_dp
  maturity = 1
  steps = 500
  strikes = [70, 80, 90, 100, 110, 120, 130]
  prices = price_strikes(strikes)
  write (*,"(a)") "strikes"
  write (*,"(*(i0, 1x))") strikes
  write (*,"(a)") "American calls"
  write (*,"(*(g0, 1x))") prices(1, :)
  write (*,"(a)") "American puts"
  write (*,"(*(g0, 1x))") prices(2, :)
end program american_options_j
