! Generated by xj2f.py 0.1.0 from black_scholes.ijs
module black_scholes_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: normal_cdf, black_scholes, spot, rate, volatility, maturity, discount
  integer :: spot, maturity
  real(kind=dp) :: rate, volatility, discount

contains

! Standard normal CDF using the Abramowitz-Stegun approximation.
! J: normal_cdf =: 3 : 0
pure elemental function normal_cdf(y) result(j_result)
  real(kind=dp), intent(in) :: y
  real(kind=dp) :: j_result
  real(kind=dp) :: t, polynomial, tail
  t = 1.0_dp / (1 + 0.2316419_dp * abs(y))
  polynomial = t * (0.319381530_dp + t * (-0.356563782_dp + t * (1.781477937_dp + t * ( &
     & -1.821255978_dp + t * 1.330274429_dp))))
  tail = (exp(-0.5_dp * y**2) / sqrt(2 * acos(-1.0_dp))) * polynomial
  if (y >= 0) then
    j_result = 1 - tail
  else
    j_result = tail
  end if
end function normal_cdf

! Return a two-row matrix: call prices followed by put prices.
! J: black_scholes =: 3 : 0
pure function black_scholes(y) result(j_result)
  integer, intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:,:)
  real(kind=dp) :: discount, vol_sqrt_t
  real(kind=dp), allocatable :: d1(:), d2(:), call_j(:), put(:)
  discount = exp(-(rate * maturity))
  vol_sqrt_t = volatility * sqrt(real(maturity, kind=dp))
  d1 = (log(real(spot, kind=dp) / y) + (rate + 0.5_dp * volatility**2) * maturity) / vol_sqrt_t
  d2 = d1 - vol_sqrt_t
  call_j = spot * normal_cdf(d1) - y * discount * normal_cdf(d2)
  put = y * discount * normal_cdf(-d2) - spot * normal_cdf(-d1)
  j_result = reshape([call_j, put], [2, size(call_j)], order=[2, 1])
end function black_scholes

end module black_scholes_j_mod

program black_scholes_j
  use black_scholes_j_mod, only: black_scholes, discount, maturity, normal_cdf, rate, spot, &
     & volatility
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer, allocatable :: strikes(:)
  integer :: n
  real(kind=dp), allocatable :: analytic(:,:), u1(:), u2(:), z(:), terminal(:), differences(:,:), &
     & mc_call(:), mc_put(:), results(:,:)
  ! Price European options analytically and by risk-neutral Monte Carlo.
  ! J: spot =: 100
  spot = 100
  rate = 0.05_dp
  volatility = 0.2_dp
  maturity = 1
  strikes = [70, 80, 90, 100, 110, 120, 130]
  n = 500000
  analytic = black_scholes(strikes)
  ! Simulate the terminal stock price under the risk-neutral distribution.
  ! J: u1 =: 1e_12 >. ? n $ 0
  allocate(u1(n), u2(n))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  z = sqrt(-2 * log(u1)) * cos(2 * acos(-1.0_dp) * u2)
  terminal = spot * exp((rate - 0.5_dp * volatility**2) * maturity + volatility * &
     & sqrt(real(maturity, kind=dp)) * z)
  ! Each column contains payoffs for one strike, using common random draws.
  ! J: discount =: ^ -rate * maturity
  discount = exp(-(rate * maturity))
  differences = spread(terminal, dim=2, ncopies=size(strikes)) - spread(strikes, dim=1, &
     & ncopies=size(terminal))
  mc_call = discount * (sum(max(0.0_dp, differences), dim=1) / n)
  mc_put = discount * (sum(max(0.0_dp, -differences), dim=1) / n)
  results = reshape([real(kind=dp) :: strikes, analytic(1, :), mc_call, analytic(2, :), mc_put], &
     & [size(strikes), 5])
  write (*,"(a)") "strike, analytic call, Monte Carlo call, analytic put, Monte Carlo put"
  write (*,"(5(g0, 1x))") transpose(results)
end program black_scholes_j
