! Generated by xj2f.py 0.1.0 from correlation.ijs
! Correlation in the model y = c*x + e.
! Both x and e are independent standard normal variates.

module correlation_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: mean, pi, y
  real(kind=dp), parameter :: pi = acos(-1.0_dp)
  real(kind=dp), allocatable :: y(:)

contains

pure function mean(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(y) / size(y, 1)
end function mean

end module correlation_j_mod

program correlation_j
  use correlation_j_mod, only: mean, pi, y
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer :: n, c
  real(kind=dp), allocatable :: u1(:), u2(:), x(:), u3(:), u4(:), e(:), x_centered(:), y_centered(:)
  real(kind=dp) :: empirical, theoretical
  n = 100000
  c = 2
  ! Generate x by the Box-Muller transform.
  ! J: u1 =: 1e_12 >. ? n $ 0
  allocate(u1(n), u2(n))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  x = sqrt(-2 * log(u1)) * cos(2 * pi * u2)
  ! Generate independent standard normal noise e.
  ! J: u3 =: 1e_12 >. ? n $ 0
  allocate(u3(n), u4(n))
  call random_number(u3)
  u3 = max(1e-12_dp, u3)
  call random_number(u4)
  e = sqrt(-2 * log(u3)) * cos(2 * pi * u4)
  y = c * x + e
  x_centered = x - mean(x)
  y_centered = y - mean(y)
  ! Pearson sample correlation.
  ! J: empirical =: (+/ x_centered * y_centered) % %: (+/ *: x_centered) * +/ *: y_centered
  empirical = sum(x_centered * y_centered) / sqrt(sum(x_centered**2) * sum(y_centered**2))
  ! Cov(x,y) = c and Var(y) = c^2 + 1.
  ! J: theoretical =: c % %: 1 + *: c
  theoretical = real(c, kind=dp) / sqrt(real(1 + c**2, kind=dp))
  write (*,"(a)") "number of simulations"
  write (*,"(i0)") n
  write (*,"(a)") "coefficient c"
  write (*,"(i0)") c
  write (*,"(a)") "empirical correlation"
  write (*,"(g0)") empirical
  write (*,"(a)") "theoretical correlation"
  write (*,"(g0)") theoretical
  write (*,"(a)") "difference"
  write (*,"(g0)") empirical - theoretical
end program correlation_j
