! Generated by xj2f.py 0.1.0 from fit_mixture_mv_general.ijs
! Matrix-oriented general-covariance mixture fitting, exercised in 4 dimensions.

module fit_mixture_mv_general_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: mv_density, component_update, fit_two_em, fit_three_em, log_likelihood_one, &
     & log_likelihood_two, log_likelihood_three, j_iota, n, dimension_j, component_size, &
     & observations, parameters1, parameters2, first, second

  interface component_update
    module procedure component_update_integer_rank1, component_update_real_rank1
  end interface
  integer :: n, dimension_j, component_size
  real(kind=dp), allocatable :: observations(:,:), parameters1(:), parameters2(:)
  integer, allocatable :: first(:), second(:)

contains

! y is weight, a dimension-vector mean, then a flattened covariance matrix.
! J: mv_density =: 3 : 0
pure function mv_density(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: covariance(:,:), centered(:,:), quadratic(:)
  real(kind=dp) :: normalizer
  covariance = reshape(y(1 + dimension_j + j_iota(dimension_j**2) + 1), [dimension_j, dimension_j] &
     & , pad=y(1 + dimension_j + j_iota(dimension_j**2) + 1), order=[2, 1])
  centered = observations - spread((y(1 + j_iota(dimension_j) + 1)), dim=1, &
     & ncopies=size(observations, 1))
  quadratic = sum(centered * matmul(centered, j_inverse_real(covariance)), dim=2)
  normalizer = (2 * acos(-1.0_dp))**(0.5_dp * dimension_j) * sqrt((max(1e-300_dp, &
     & j_determinant_real(covariance))))
  j_result = max(1e-300_dp, exp(-0.5_dp * quadratic) / normalizer)
end function mv_density

! The ridge makes the weighted covariance strictly positive definite.
! J: component_update =: 3 : 0
pure function component_update_integer_rank1(y) result(j_result)
  integer, intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  integer, allocatable :: weights(:)
  integer :: weight_sum
  real(kind=dp) :: weight, ridge
  real(kind=dp), allocatable :: mean(:), centered(:,:), weighted_centered(:,:), covariance(:,:)
  weights = y
  weight_sum = sum(weights)
  weight = real(weight_sum, kind=dp) / n
  mean = (matmul(weights, observations)) / weight_sum
  centered = observations - spread(mean, dim=1, ncopies=size(observations, 1))
  weighted_centered = spread(weights, dim=2, ncopies=size(centered, 2)) * centered
  covariance = (matmul(transpose(centered), weighted_centered)) / weight_sum
  ridge = 1e-8_dp * max(1.0_dp, sum(j_diagonal_real(covariance)) / dimension_j)
  covariance = covariance + ridge * (merge(1, 0, spread(j_iota(dimension_j), dim=2, &
     & ncopies=size(j_iota(dimension_j))) == spread(j_iota(dimension_j), dim=1, &
     & ncopies=size(j_iota(dimension_j)))))
  j_result = [real(kind=dp) :: weight, [real(kind=dp) :: mean, reshape(transpose(covariance), &
     & [size(covariance)])]]
end function component_update_integer_rank1

pure function component_update_real_rank1(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: weights(:), mean(:), centered(:,:), weighted_centered(:,:), &
     & covariance(:,:)
  real(kind=dp) :: weight_sum, weight, ridge
  weights = y
  weight_sum = sum(weights)
  weight = weight_sum / n
  mean = (matmul(weights, observations)) / weight_sum
  centered = observations - spread(mean, dim=1, ncopies=size(observations, 1))
  weighted_centered = spread(weights, dim=2, ncopies=size(centered, 2)) * centered
  covariance = (matmul(transpose(centered), weighted_centered)) / weight_sum
  ridge = 1e-8_dp * max(1.0_dp, sum(j_diagonal_real(covariance)) / dimension_j)
  covariance = covariance + ridge * (merge(1, 0, spread(j_iota(dimension_j), dim=2, &
     & ncopies=size(j_iota(dimension_j))) == spread(j_iota(dimension_j), dim=1, &
     & ncopies=size(j_iota(dimension_j)))))
  j_result = [real(kind=dp) :: weight, [real(kind=dp) :: mean, reshape(transpose(covariance), &
     & [size(covariance)])]]
end function component_update_real_rank1

pure function fit_two_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), parameters1(:), parameters2(:), weighted1(:), &
     & weighted2(:), total_density(:), update1(:), update2(:), new_parameters(:)
  integer, allocatable :: first(:), second(:)
  integer :: iteration
  parameters = y
  first = j_iota(component_size)
  second = component_size + j_iota(component_size)
  do iteration = 0, 200 - 1
    parameters1 = parameters(first + 1)
    parameters2 = parameters(second + 1)
    weighted1 = parameters1(1) * mv_density(parameters1)
    weighted2 = parameters2(1) * mv_density(parameters2)
    total_density = max(1e-300_dp, weighted1 + weighted2)
    update1 = component_update(weighted1 / total_density)
    update2 = component_update(weighted2 / total_density)
    new_parameters = [real(kind=dp) :: update1, update2]
    if (1e-8_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_two_em

pure function fit_three_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), parameters1(:), parameters2(:), parameters3(:), &
     & weighted1(:), weighted2(:), weighted3(:), total_density(:), update1(:), update2(:), &
     & update3(:), new_parameters(:)
  integer, allocatable :: first(:), second(:), third(:)
  integer :: iteration
  parameters = y
  first = j_iota(component_size)
  second = component_size + j_iota(component_size)
  third = 2 * component_size + j_iota(component_size)
  do iteration = 0, 250 - 1
    parameters1 = parameters(first + 1)
    parameters2 = parameters(second + 1)
    parameters3 = parameters(third + 1)
    weighted1 = parameters1(1) * mv_density(parameters1)
    weighted2 = parameters2(1) * mv_density(parameters2)
    weighted3 = parameters3(1) * mv_density(parameters3)
    total_density = max(1e-300_dp, weighted1 + weighted2 + weighted3)
    update1 = component_update(weighted1 / total_density)
    update2 = component_update(weighted2 / total_density)
    update3 = component_update(weighted3 / total_density)
    new_parameters = [real(kind=dp) :: update1, [real(kind=dp) :: update2, update3]]
    if (1e-8_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_three_em

pure function log_likelihood_one(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(log(mv_density(y)))
end function log_likelihood_one

pure function log_likelihood_two(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp), allocatable :: parameters1(:), parameters2(:), density2(:)
  parameters1 = y(j_iota(component_size) + 1)
  parameters2 = y((component_size + j_iota(component_size)) + 1)
  density2 = parameters2(1) * mv_density(parameters2)
  j_result = sum(log(max(1e-300_dp, (parameters1(1) * mv_density(parameters1)) + density2)))
end function log_likelihood_two

pure function log_likelihood_three(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp), allocatable :: parameters1(:), parameters2(:), parameters3(:), density2(:), &
     & density3(:)
  parameters1 = y(j_iota(component_size) + 1)
  parameters2 = y((component_size + j_iota(component_size)) + 1)
  parameters3 = y((2 * component_size + j_iota(component_size)) + 1)
  density2 = parameters2(1) * mv_density(parameters2)
  density3 = parameters3(1) * mv_density(parameters3)
  j_result = sum(log(max(1e-300_dp, (parameters1(1) * mv_density(parameters1)) + density2 + &
     & density3)))
end function log_likelihood_three

pure function j_diagonal_real(matrix) result(values)
  real(kind=dp), intent(in) :: matrix(:,:)
  real(kind=dp), allocatable :: values(:)
  integer :: diagonal_index, diagonal_size
  diagonal_size = min(size(matrix, 1), size(matrix, 2))
  allocate(values(diagonal_size))
  do diagonal_index = 1, diagonal_size
    values(diagonal_index) = matrix(diagonal_index, diagonal_index)
  end do
end function j_diagonal_real

pure function j_inverse_real(matrix) result(inverse)
  real(kind=dp), intent(in) :: matrix(:,:)
  real(kind=dp), allocatable :: inverse(:,:)
  real(kind=dp), allocatable :: work(:,:), row_buffer(:)
  real(kind=dp) :: factor, pivot
  integer :: column, matrix_size, pivot_row, row
  matrix_size = size(matrix, 1)
  if (size(matrix, 2) /= matrix_size) error stop "matrix inverse requires a square matrix"
  work = matrix
  allocate(inverse(matrix_size, matrix_size), row_buffer(matrix_size))
  inverse = 0.0_dp
  do row = 1, matrix_size
    inverse(row, row) = 1.0_dp
  end do
  do column = 1, matrix_size
    pivot_row = column - 1 + maxloc(abs(work(column:matrix_size, column)), dim=1)
    pivot = work(pivot_row, column)
    if (abs(pivot) <= tiny(1.0_dp)) error stop "singular matrix"
    if (pivot_row /= column) then
      row_buffer = work(column, :)
      work(column, :) = work(pivot_row, :)
      work(pivot_row, :) = row_buffer
      row_buffer = inverse(column, :)
      inverse(column, :) = inverse(pivot_row, :)
      inverse(pivot_row, :) = row_buffer
    end if
    pivot = work(column, column)
    work(column, :) = work(column, :) / pivot
    inverse(column, :) = inverse(column, :) / pivot
    do row = 1, matrix_size
      if (row == column) cycle
      factor = work(row, column)
      work(row, :) = work(row, :) - factor * work(column, :)
      inverse(row, :) = inverse(row, :) - factor * inverse(column, :)
    end do
  end do
end function j_inverse_real

pure function j_determinant_real(matrix) result(determinant)
  real(kind=dp), intent(in) :: matrix(:,:)
  real(kind=dp) :: determinant
  real(kind=dp), allocatable :: work(:,:), row_buffer(:)
  real(kind=dp) :: factor
  integer :: column, matrix_size, pivot_row, row, sign_factor
  matrix_size = size(matrix, 1)
  if (size(matrix, 2) /= matrix_size) error stop "determinant requires a square matrix"
  work = matrix
  allocate(row_buffer(matrix_size))
  sign_factor = 1
  do column = 1, matrix_size
    pivot_row = column - 1 + maxloc(abs(work(column:matrix_size, column)), dim=1)
    if (abs(work(pivot_row, column)) <= tiny(1.0_dp)) then
      determinant = 0.0_dp
      return
    end if
    if (pivot_row /= column) then
      row_buffer = work(column, :)
      work(column, :) = work(pivot_row, :)
      work(pivot_row, :) = row_buffer
      sign_factor = -sign_factor
    end if
    do row = column + 1, matrix_size
      factor = work(row, column) / work(column, column)
      work(row, column:matrix_size) = &
        work(row, column:matrix_size) - &
        factor * work(column, column:matrix_size)
    end do
  end do
  determinant = real(sign_factor, kind=dp)
  do column = 1, matrix_size
    determinant = determinant * work(column, column)
  end do
end function j_determinant_real

pure function j_iota(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:)
  integer :: value_index
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n))
  do value_index = 1, n
    values(value_index) = value_index - 1
  end do
end function j_iota

end module fit_mixture_mv_general_j_mod

program fit_mixture_mv_general_j
  use fit_mixture_mv_general_j_mod, only: component_size, component_update, dimension_j, first, &
     & fit_three_em, fit_two_em, j_iota, log_likelihood_one, log_likelihood_three, &
     & log_likelihood_two, mv_density, n, observations, parameters1, parameters2, second
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  real(kind=dp) :: true_weight, split_weight, parameters_per_component
  real(kind=dp), allocatable :: true_mean1(:), true_mean2(:), true_cholesky1(:,:), &
     & true_cholesky2(:,:), true_covariance1(:,:), true_covariance2(:,:), u1(:,:), u2(:,:), z(:,:) &
     & , sample1(:,:), sample2(:,:), one_fit(:), global_mean(:), initial_covariance(:,:), &
     & direction(:), two_fit(:), fitted1(:), fitted2(:), split_direction(:), split1(:), split2(:), &
     & three_fit(:), log_likelihoods(:), parameter_counts(:), aic(:), bic(:)
  logical, allocatable :: component1(:)
  real(kind=dp), allocatable :: j_random_1(:)
  n = 20000
  dimension_j = 4
  component_size = 1 + dimension_j + dimension_j**2
  ! Generate a two-component mixture from positive-diagonal Cholesky factors.
  ! J: true_weight =: 0.4
  true_weight = 0.4_dp
  true_mean1 = [real(kind=dp) :: -1, -0.5_dp, 0, 0.5_dp]
  true_mean2 = [real(kind=dp) :: 2, 1.5_dp, 1, 0.5_dp]
  true_cholesky1 = reshape([real(kind=dp) :: 0.8_dp, 0, 0, 0, 0.2_dp, 0.7_dp, 0, 0, -0.1_dp, &
     & 0.25_dp, 0.6_dp, 0, 0.1_dp, -0.05_dp, 0.2_dp, 0.65_dp], [4, 4], order=[2, 1])
  true_cholesky2 = reshape([real(kind=dp) :: 1.1_dp, 0, 0, 0, 0.4_dp, 0.9_dp, 0, 0, 0.2_dp, &
     & -0.15_dp, 0.8_dp, 0, -0.1_dp, 0.2_dp, 0.3_dp, 0.75_dp], [4, 4], order=[2, 1])
  true_covariance1 = matmul(true_cholesky1, transpose(true_cholesky1))
  true_covariance2 = matmul(true_cholesky2, transpose(true_cholesky2))
  ! Box-Muller produces an n by dimension matrix of independent normals.
  ! J: u1 =: 1e_12 >. ? (n, dimension) $ 0
  allocate(u1(n, dimension_j), u2(n, dimension_j))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  z = sqrt(-2 * log(u1)) * cos(2 * acos(-1.0_dp) * u2)
  sample1 = spread(true_mean1, dim=1, &
     & ncopies=size(matmul(z, transpose(true_cholesky1)), 1)) + matmul(z, transpose(true_cholesky1))
  sample2 = spread(true_mean2, dim=1, &
     & ncopies=size(matmul(z, transpose(true_cholesky2)), 1)) + matmul(z, transpose(true_cholesky2))
  allocate(j_random_1(n))
  call random_number(j_random_1)
  component1 = j_random_1 < true_weight
  observations = spread(merge(1, 0, component1), dim=2, &
     & ncopies=size(sample1, 2)) * sample1 + spread(1 - merge(1, 0, component1), dim=2, &
     & ncopies=size(sample2, 2)) * sample2
  ! Fit one component, then initialize two separated components.
  ! J: one_fit =: component_update 1 + 0 * component1
  one_fit = component_update(1 + 0 * merge(1, 0, component1))
  global_mean = one_fit(1 + j_iota(dimension_j) + 1)
  initial_covariance = 0.8_dp * (merge(1, 0, spread(j_iota(dimension_j), dim=2, &
     & ncopies=size(j_iota(dimension_j))) == spread(j_iota(dimension_j), dim=1, &
     & ncopies=size(j_iota(dimension_j)))))
  direction = [real(kind=dp) :: -1.5_dp, -1, -0.5_dp, 0]
  parameters1 = [real(kind=dp) :: 0.4_dp, [real(kind=dp) :: global_mean + direction, &
     & reshape(transpose(initial_covariance), [size(initial_covariance)])]]
  parameters2 = [real(kind=dp) :: 0.6_dp, [real(kind=dp) :: global_mean - 0.6666666667_dp * &
     & direction, reshape(transpose(initial_covariance), [size(initial_covariance)])]]
  two_fit = fit_two_em([real(kind=dp) :: parameters1, parameters2])
  ! Split the second fitted component to initialize three components.
  ! J: first =: i. component_size
  first = j_iota(component_size)
  second = component_size + j_iota(component_size)
  fitted1 = two_fit(first + 1)
  fitted2 = two_fit(second + 1)
  split_weight = 0.5_dp * fitted2(1)
  split_direction = [0.2_dp, -0.2_dp, 0.2_dp, -0.2_dp]
  split1 = [real(kind=dp) :: split_weight, [real(kind=dp) :: fitted2(1 + j_iota(dimension_j) + 1) &
     & + split_direction, fitted2(1 + dimension_j + j_iota(dimension_j**2) + 1)]]
  split2 = [real(kind=dp) :: split_weight, [real(kind=dp) :: fitted2(1 + j_iota(dimension_j) + 1) &
     & - split_direction, fitted2(1 + dimension_j + j_iota(dimension_j**2) + 1)]]
  three_fit = fit_three_em([real(kind=dp) :: fitted1, [real(kind=dp) :: split1, split2]])
  log_likelihoods = [real(kind=dp) :: log_likelihood_one(one_fit), [real(kind=dp) :: &
     & log_likelihood_two(two_fit), log_likelihood_three(three_fit)]]
  parameters_per_component = dimension_j + real(dimension_j * (dimension_j + 1), kind=dp) / 2
  parameter_counts = [0, 1, 2] + [1, 2, 3] * parameters_per_component
  aic = 2 * parameter_counts - 2 * log_likelihoods
  bic = log(real(n, kind=dp)) * parameter_counts - 2 * log_likelihoods
  write (*,"(a)") "dimension and sample size"
  write (*,"(*(i0, 1x))") [dimension_j, n]
  write (*,"(a,1(/,a))") "number of components: 1 2 3", "log likelihood"
  write (*,"(*(g0, 1x))") log_likelihoods
  write (*,"(a)") "AIC"
  write (*,"(*(g0, 1x))") aic
  write (*,"(a)") "BIC"
  write (*,"(*(g0, 1x))") bic
  write (*,"(a)") "components chosen by AIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, aic == minval(aic))))
  write (*,"(a)") "components chosen by BIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, bic == minval(bic))))
  write (*,"(a)") "true means"
  write (*,"(*(g0, 1x))") true_mean1
  write (*,"(*(g0, 1x))") true_mean2
  write (*,"(a)") "fitted two-component parameter blocks"
  write (*,"(*(g0, 1x))") fitted1
  write (*,"(*(g0, 1x))") fitted2
end program fit_mixture_mv_general_j
