! Generated by xj2f.py 0.1.0 from fit_mixture_moments.ijs
module fit_mixture_moments_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: mean, mixture_moments, moment_jacobian, fit_mixture, sample_moments, moment_scale
  real(kind=dp), allocatable :: sample_moments(:), moment_scale(:)

contains

pure function mean(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(y) / size(y, 1)
end function mean

! The optimizer uses unconstrained parameters
! alpha, mu1, log(sd1), mu2, log(sd2).
! The logistic transform maps alpha to a mixture weight in (0,1).
! J: mixture_moments =: 3 : 0
pure function mixture_moments(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp) :: mu1, sd1, mu2, sd2, weight
  real(kind=dp), allocatable :: component1_moments(:), component2_moments(:)
  mu1 = y(2)
  sd1 = exp(y(3))
  mu2 = y(4)
  sd2 = exp(y(5))
  weight = 1.0_dp / (1 + exp(-y(1)))
  component1_moments = [real(kind=dp) :: mu1, [real(kind=dp) :: mu1**2 + sd1**2, [real(kind=dp) :: &
     & mu1**3 + 3 * mu1 * sd1**2, [real(kind=dp) :: mu1**4 + 6 * mu1**2 * sd1**2 + 3 * sd1**4, &
     & mu1**5 + 10 * mu1**3 * sd1**2 + 15 * mu1 * sd1**4]]]]
  component2_moments = [real(kind=dp) :: mu2, [real(kind=dp) :: mu2**2 + sd2**2, [real(kind=dp) :: &
     & mu2**3 + 3 * mu2 * sd2**2, [real(kind=dp) :: mu2**4 + 6 * mu2**2 * sd2**2 + 3 * sd2**4, &
     & mu2**5 + 10 * mu2**3 * sd2**2 + 15 * mu2 * sd2**4]]]]
  j_result = weight * component1_moments + (1 - weight) * component2_moments
end function mixture_moments

! Form a numerical 5 by 5 Jacobian of the scaled moment residuals.
! J: moment_jacobian =: 3 : 0
pure function moment_jacobian(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:,:)
  real(kind=dp) :: step_size
  real(kind=dp), allocatable :: base(:), jacobian(:,:), shifted(:), column(:)
  integer :: parameter_j
  step_size = 1e-5_dp
  base = mixture_moments(y)
  jacobian = reshape([0.0_dp], [5, 5], pad=[0.0_dp], order=[2, 1])
  do parameter_j = 0, 5 - 1
    shifted = y + step_size * (merge(1, 0, parameter_j == j_iota(5)))
    column = (mixture_moments(shifted) - base) / (step_size * moment_scale)
    jacobian = jacobian + spread(column, dim=2, ncopies=size(merge(1, 0, &
       & parameter_j == j_iota(5)))) * spread(merge(1, 0, parameter_j == j_iota(5)), dim=1, &
       & ncopies=size(column))
  end do
  j_result = jacobian
end function moment_jacobian

! Damped Gauss-Newton iteration for the five moment equations.
! J: fit_mixture =: 3 : 0
pure function fit_mixture(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), residual(:), jacobian(:,:), normal_matrix(:,:), &
     & normal_rhs(:), update(:)
  logical, allocatable :: identity(:,:)
  real(kind=dp) :: damping
  integer :: iteration
  parameters = y
  identity = spread(j_iota(5), dim=2, ncopies=size(j_iota(5))) == spread(j_iota(5), dim=1, &
     & ncopies=size(j_iota(5)))
  damping = 0.01_dp
  do iteration = 0, 100 - 1
    residual = (sample_moments - mixture_moments(parameters)) / moment_scale
    jacobian = moment_jacobian(parameters)
    normal_matrix = matmul(transpose(jacobian), jacobian) + damping * merge(1, 0, identity)
    normal_rhs = matmul(transpose(jacobian), residual)
    update = j_solve_real_vector(normal_rhs, normal_matrix)
    parameters = parameters + update
    if (1e-9_dp > maxval(abs(update))) then
      exit
    end if
  end do
  j_result = parameters
end function fit_mixture

pure function j_multiplication_table_int(left, right) result(table_values)
  integer, intent(in) :: left(:), right(:)
  integer, allocatable :: table_values(:,:)
  integer :: row_index
  allocate(table_values(size(left), size(right)))
  do row_index = 1, size(left)
    table_values(row_index, :) = left(row_index) * right
  end do
end function j_multiplication_table_int

pure function j_solve_real_vector(rhs, coefficients) result(solution)
  real(kind=dp), intent(in) :: rhs(:), coefficients(:,:)
  real(kind=dp), allocatable :: solution(:)
  real(kind=dp), allocatable :: work(:,:), work_rhs(:), row_buffer(:)
  real(kind=dp) :: factor, scalar_buffer
  integer :: column, row, pivot_row, system_size
  system_size = size(rhs)
  if (size(coefficients, 1) /= system_size .or. &
      size(coefficients, 2) /= system_size) &
    error stop "linear solve shape mismatch"
  work = coefficients
  work_rhs = rhs
  allocate(solution(system_size), row_buffer(system_size))
  do column = 1, system_size
    pivot_row = column - 1 + maxloc(abs(work(column:system_size, column)), dim=1)
    if (abs(work(pivot_row, column)) <= tiny(1.0_dp)) error stop "singular matrix"
    if (pivot_row /= column) then
      row_buffer = work(column, :)
      work(column, :) = work(pivot_row, :)
      work(pivot_row, :) = row_buffer
      scalar_buffer = work_rhs(column)
      work_rhs(column) = work_rhs(pivot_row)
      work_rhs(pivot_row) = scalar_buffer
    end if
    do row = column + 1, system_size
      factor = work(row, column) / work(column, column)
      work(row, column:system_size) = work(row, column:system_size) - &
        factor * work(column, column:system_size)
      work_rhs(row) = work_rhs(row) - factor * work_rhs(column)
    end do
  end do
  do row = system_size, 1, -1
    solution(row) = work_rhs(row)
    if (row < system_size) solution(row) = solution(row) - &
      dot_product(work(row, row + 1:system_size), &
                  solution(row + 1:system_size))
    solution(row) = solution(row) / work(row, row)
  end do
end function j_solve_real_vector

pure function j_iota(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:)
  integer :: value_index
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n))
  do value_index = 1, n
    values(value_index) = value_index - 1
  end do
end function j_iota

end module fit_mixture_moments_j_mod

program fit_mixture_moments_j
  use fit_mixture_moments_j_mod, only: fit_mixture, mean, mixture_moments, moment_jacobian, &
     & moment_scale, sample_moments
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer :: n, true_mu1, true_mu2
  real(kind=dp) :: true_weight, true_sd1, true_sd2, fitted_weight, fitted_mu1, fitted_sd1, &
     & fitted_mu2, fitted_sd2
  real(kind=dp), allocatable :: u1(:), u2(:), z1(:), u3(:), u4(:), z2(:), x1(:), x2(:), x(:), &
     & initial(:), fitted_internal(:)
  logical, allocatable :: component1(:)
  real(kind=dp), allocatable :: j_random_1(:)
  ! Fit a two-normal mixture by matching empirical raw moments 1 through 5.
  ! J: n =: 200000
  n = 200000
  ! Parameters used to generate the sample.
  ! J: true_weight =: 0.35
  true_weight = 0.35_dp
  true_mu1 = -1
  true_sd1 = 0.8_dp
  true_mu2 = 2
  true_sd2 = 1.3_dp
  ! Generate two independent standard normal samples by Box-Muller.
  ! J: u1 =: 1e_12 >. ? n $ 0
  allocate(u1(n), u2(n))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  z1 = sqrt(-2 * log(u1)) * cos(2 * acos(-1.0_dp) * u2)
  allocate(u3(n), u4(n))
  call random_number(u3)
  u3 = max(1e-12_dp, u3)
  call random_number(u4)
  z2 = sqrt(-2 * log(u3)) * cos(2 * acos(-1.0_dp) * u4)
  ! Select a component independently for each observation.
  ! J: component1 =: (? n $ 0) < true_weight
  allocate(j_random_1(n))
  call random_number(j_random_1)
  component1 = j_random_1 < true_weight
  x1 = true_mu1 + true_sd1 * z1
  x2 = true_mu2 + true_sd2 * z2
  x = merge(1, 0, component1) * x1 + (1 - merge(1, 0, component1)) * x2
  sample_moments = [real(kind=dp) :: mean(x), [real(kind=dp) :: mean(x**2), [real(kind=dp) :: &
     & mean(x**3), [real(kind=dp) :: mean(x**4), mean(x**5)]]]]
  moment_scale = max(1.0_dp, abs(sample_moments))
  ! Starting values identify component 1 as the lower-mean component.
  ! J: initial =: _0.4 _0.7 _0.1 1.7 0.1
  initial = [-0.4_dp, -0.7_dp, -0.1_dp, 1.7_dp, 0.1_dp]
  fitted_internal = fit_mixture(initial)
  fitted_weight = 1.0_dp / (1 + exp(-fitted_internal(1)))
  fitted_mu1 = fitted_internal(2)
  fitted_sd1 = exp(fitted_internal(3))
  fitted_mu2 = fitted_internal(4)
  fitted_sd2 = exp(fitted_internal(5))
  write (*,"(a)") "sample size"
  write (*,"(i0)") n
  write (*,"(a,1(/,a))") "parameter: fitted theoretical difference", "component 1 weight"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: fitted_weight, [real(kind=dp) :: true_weight, &
     & fitted_weight - true_weight]]
  write (*,"(a)") "component 1 mean"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: fitted_mu1, [real(kind=dp) :: true_mu1, fitted_mu1 - &
     & true_mu1]]
  write (*,"(a)") "component 1 standard deviation"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: fitted_sd1, [real(kind=dp) :: true_sd1, fitted_sd1 - &
     & true_sd1]]
  write (*,"(a)") "component 2 mean"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: fitted_mu2, [real(kind=dp) :: true_mu2, fitted_mu2 - &
     & true_mu2]]
  write (*,"(a)") "component 2 standard deviation"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: fitted_sd2, [real(kind=dp) :: true_sd2, fitted_sd2 - &
     & true_sd2]]
  write (*,"(a)") "empirical moments 1 through 5"
  write (*,"(*(g0, 1x))") sample_moments
  write (*,"(a)") "moments implied by fitted parameters"
  write (*,"(*(g0, 1x))") mixture_moments(fitted_internal)
end program fit_mixture_moments_j
