! Generated by xj2f.py 0.1.0 from fit_mixture_mv.ijs
module fit_mixture_mv_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: covariance_is_pd, mv_density, component_update, fit_two_em, fit_three_em, &
     & log_likelihood_one, log_likelihood_two, log_likelihood_three, n, xa, xb, xc, j_iota
  integer :: n
  real(kind=dp), allocatable :: xa(:), xb(:), xc(:)

contains

! Sylvester's criterion for a symmetric 3 by 3 covariance matrix.
! J: covariance_is_pd =: 3 : 0
pure function covariance_is_pd(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  logical :: j_result
  real(kind=dp) :: s11, s22, s33, s12, s13, s23, determinant
  s11 = y(1)
  s22 = y(2)
  s33 = y(3)
  s12 = y(4)
  s13 = y(5)
  s23 = y(6)
  determinant = (s11 * s22 * s33 + 2 * s12 * s13 * s23) - (s11 * s23**2 + s22 * s13**2 + s33 * &
     & s12**2)
  j_result = s11 > 0 .and. (s11 * s22 - s12**2) > 0 .and. determinant > 0
end function covariance_is_pd

! y contains three means followed by six unique covariance entries.
! J: mv_density =: 3 : 0
pure function mv_density(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp) :: s11, s22, s33, s12, s13, s23, c11, c22, c33, c12, c13, c23, determinant
  real(kind=dp), allocatable :: da(:), db(:), dc(:), quadratic(:)
  s11 = y(4)
  s22 = y(5)
  s33 = y(6)
  s12 = y(7)
  s13 = y(8)
  s23 = y(9)
  da = xa - y(1)
  db = xb - y(2)
  dc = xc - y(3)
  c11 = s22 * s33 - s23**2
  c22 = s11 * s33 - s13**2
  c33 = s11 * s22 - s12**2
  c12 = s13 * s23 - s12 * s33
  c13 = s12 * s23 - s13 * s22
  c23 = s12 * s13 - s11 * s23
  determinant = max(1e-300_dp, (s11 * s22 * s33 + 2 * s12 * s13 * s23) - (s11 * s23**2 + s22 * &
     & s13**2 + s33 * s12**2))
  quadratic = (c11 * da**2 + c22 * db**2 + c33 * dc**2 + 2 * c12 * da * db + 2 * c13 * da * dc + 2 &
     & * c23 * db * dc) / determinant
  j_result = max(1e-300_dp, exp(-0.5_dp * quadratic) / (15.7496099457_dp * sqrt(determinant)))
end function mv_density

! A weighted M-step returns weight, means, and a regularized covariance.
! J: component_update =: 3 : 0
pure function component_update(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: responsibility(:), da(:), db(:), dc(:)
  real(kind=dp) :: responsibility_sum, weight, mua, mub, muc, s11, s22, s33, s12, s13, s23, ridge
  responsibility = y
  responsibility_sum = sum(responsibility)
  weight = responsibility_sum / n
  mua = sum(responsibility * xa) / responsibility_sum
  mub = sum(responsibility * xb) / responsibility_sum
  muc = sum(responsibility * xc) / responsibility_sum
  da = xa - mua
  db = xb - mub
  dc = xc - muc
  s11 = sum(responsibility * da**2) / responsibility_sum
  s22 = sum(responsibility * db**2) / responsibility_sum
  s33 = sum(responsibility * dc**2) / responsibility_sum
  s12 = sum(responsibility * da * db) / responsibility_sum
  s13 = sum(responsibility * da * dc) / responsibility_sum
  s23 = sum(responsibility * db * dc) / responsibility_sum
  ridge = 1e-8_dp * max(1.0_dp, (s11 + s22 + s33) / 3)
  s11 = s11 + ridge
  s22 = s22 + ridge
  s33 = s33 + ridge
  j_result = [real(kind=dp) :: weight, [real(kind=dp) :: mua, [real(kind=dp) :: mub, [real(kind=dp &
     & ) :: muc, [real(kind=dp) :: s11, [real(kind=dp) :: s22, [real(kind=dp) :: s33, [real(kind &
     & =dp) :: s12, [real(kind=dp) :: s13, s23]]]]]]]]]
end function component_update

pure function fit_two_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), component1_parameters(:), component2_parameters(:), &
     & density1(:), density2(:), weighted1(:), weighted2(:), total_density(:), update1(:), &
     & update2(:), new_parameters(:)
  integer :: iteration
  real(kind=dp) :: weight1, weight2
  parameters = y
  do iteration = 0, 200 - 1
    weight1 = parameters(1)
    weight2 = parameters(11)
    component1_parameters = parameters([2, 3, 4, 5, 6, 7, 8, 9, 10])
    component2_parameters = parameters([12, 13, 14, 15, 16, 17, 18, 19, 20])
    density1 = mv_density(component1_parameters)
    density2 = mv_density(component2_parameters)
    weighted1 = weight1 * density1
    weighted2 = weight2 * density2
    total_density = max(1e-300_dp, weighted1 + weighted2)
    update1 = component_update(weighted1 / total_density)
    update2 = component_update(weighted2 / total_density)
    new_parameters = [real(kind=dp) :: update1, update2]
    if (1e-8_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_two_em

pure function fit_three_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), component1_parameters(:), component2_parameters(:), &
     & component3_parameters(:), density1(:), density2(:), density3(:), weighted1(:), weighted2(:) &
     & , weighted3(:), total_density(:), update1(:), update2(:), update3(:), new_parameters(:)
  integer :: iteration
  real(kind=dp) :: weight1, weight2, weight3
  parameters = y
  do iteration = 0, 250 - 1
    weight1 = parameters(1)
    weight2 = parameters(11)
    weight3 = parameters(21)
    component1_parameters = parameters([2, 3, 4, 5, 6, 7, 8, 9, 10])
    component2_parameters = parameters([12, 13, 14, 15, 16, 17, 18, 19, 20])
    component3_parameters = parameters([22, 23, 24, 25, 26, 27, 28, 29, 30])
    density1 = mv_density(component1_parameters)
    density2 = mv_density(component2_parameters)
    density3 = mv_density(component3_parameters)
    weighted1 = weight1 * density1
    weighted2 = weight2 * density2
    weighted3 = weight3 * density3
    total_density = max(1e-300_dp, weighted1 + weighted2 + weighted3)
    update1 = component_update(weighted1 / total_density)
    update2 = component_update(weighted2 / total_density)
    update3 = component_update(weighted3 / total_density)
    new_parameters = [real(kind=dp) :: update1, [real(kind=dp) :: update2, update3]]
    if (1e-8_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_three_em

pure function log_likelihood_one(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(log((mv_density(y([2, 3, 4, 5, 6, 7, 8, 9, 10])))))
end function log_likelihood_one

pure function log_likelihood_two(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp), allocatable :: density2(:)
  density2 = y(11) * mv_density(y([12, 13, 14, 15, 16, 17, 18, 19, 20]))
  j_result = sum(log(max(1e-300_dp, (y(1) * mv_density(y([2, 3, 4, 5, 6, 7, 8, 9, 10]))) + &
     & density2)))
end function log_likelihood_two

pure function log_likelihood_three(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp), allocatable :: density2(:), density3(:)
  density2 = y(11) * mv_density(y([12, 13, 14, 15, 16, 17, 18, 19, 20]))
  density3 = y(21) * mv_density(y([22, 23, 24, 25, 26, 27, 28, 29, 30]))
  j_result = sum(log(max(1e-300_dp, (y(1) * mv_density(y([2, 3, 4, 5, 6, 7, 8, 9, 10]))) + &
     & density2 + density3)))
end function log_likelihood_three

pure function j_iota(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:)
  integer :: value_index
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n))
  do value_index = 1, n
    values(value_index) = value_index - 1
  end do
end function j_iota

end module fit_mixture_mv_j_mod

program fit_mixture_mv_j
  use fit_mixture_mv_j_mod, only: component_update, covariance_is_pd, fit_three_em, fit_two_em, &
     & j_iota, log_likelihood_one, log_likelihood_three, log_likelihood_two, mv_density, n, xa, xb &
     & , xc
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer :: dimension_j
  real(kind=dp) :: true_weight, l11_1, l21_1, l22_1, l31_1, l32_1, l33_1, l11_2, l21_2, l22_2, &
     & l31_2, l32_2, l33_2, global_mua, global_mub, global_muc, split_weight, split_scale
  real(kind=dp), allocatable :: true_means1(:), true_means2(:), true_covariance1(:), &
     & true_covariance2(:), u1(:), u2(:), z1(:), u3(:), u4(:), z2(:), u5(:), u6(:), z3(:), xa1(:), &
     & xb1(:), xc1(:), xa2(:), xb2(:), xc2(:), one_fit(:), initial_covariance(:), two_initial(:), &
     & two_fit(:), split_covariance(:), three_initial(:), three_fit(:), log_likelihoods(:), aic(:) &
     & , bic(:)
  logical, allocatable :: component1(:)
  integer, allocatable :: parameter_counts(:)
  real(kind=dp), allocatable :: j_random_1(:)
  ! Simulate and fit 3-dimensional normal mixtures with general covariance matrices.
  ! J: n =: 50000
  n = 50000
  dimension_j = 3
  ! The sample comes from a two-component normal mixture.
  ! J: true_weight =: 0.4
  true_weight = 0.4_dp
  true_means1 = [real(kind=dp) :: -1, -0.5_dp, 0]
  true_means2 = [real(kind=dp) :: 2, 1.5_dp, 1]
  ! Lower triangular Cholesky factors guarantee positive definite covariances.
  ! J: l11_1 =: 0.8
  l11_1 = 0.8_dp
  l21_1 = 0.2_dp
  l22_1 = 0.7_dp
  l31_1 = -0.1_dp
  l32_1 = 0.25_dp
  l33_1 = 0.6_dp
  l11_2 = 1.1_dp
  l21_2 = 0.4_dp
  l22_2 = 0.9_dp
  l31_2 = 0.2_dp
  l32_2 = -0.15_dp
  l33_2 = 0.8_dp
  ! Covariance order is s11, s22, s33, s12, s13, s23.
  ! J: true_covariance1 =: (l11_1 ^ 2) , ((l21_1 ^ 2) + l22_1 ^ 2) , ((l31_1 ^ 2) + (l32_1 ^ 2) +
  ! l33_1 ^ 2) , (l11_1 * l21_1) , (l11_1 * l31_1) , (l21_1 * l31_1) + l22_1 * l32_1
  true_covariance1 = [real(kind=dp) :: l11_1**2, [real(kind=dp) :: l21_1**2 + l22_1**2, [real(kind &
     & =dp) :: l31_1**2 + l32_1**2 + l33_1**2, [real(kind=dp) :: l11_1 * l21_1, [real(kind=dp) :: &
     & l11_1 * l31_1, l21_1 * l31_1 + l22_1 * l32_1]]]]]
  true_covariance2 = [real(kind=dp) :: l11_2**2, [real(kind=dp) :: l21_2**2 + l22_2**2, [real(kind &
     & =dp) :: l31_2**2 + l32_2**2 + l33_2**2, [real(kind=dp) :: l11_2 * l21_2, [real(kind=dp) :: &
     & l11_2 * l31_2, l21_2 * l31_2 + l22_2 * l32_2]]]]]
  ! Generate three independent standard normal vectors by Box-Muller.
  ! J: u1 =: 1e_12 >. ? n $ 0
  allocate(u1(n), u2(n))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  z1 = sqrt(-2 * log(u1)) * cos(2 * acos(-1.0_dp) * u2)
  allocate(u3(n), u4(n))
  call random_number(u3)
  u3 = max(1e-12_dp, u3)
  call random_number(u4)
  z2 = sqrt(-2 * log(u3)) * cos(2 * acos(-1.0_dp) * u4)
  allocate(u5(n), u6(n))
  call random_number(u5)
  u5 = max(1e-12_dp, u5)
  call random_number(u6)
  z3 = sqrt(-2 * log(u5)) * cos(2 * acos(-1.0_dp) * u6)
  ! Transform independent normals by each component's Cholesky factor.
  ! J: xa1 =: (0 { true_means1) + l11_1 * z1
  xa1 = true_means1(1) + l11_1 * z1
  xb1 = true_means1(2) + l21_1 * z1 + l22_1 * z2
  xc1 = true_means1(3) + l31_1 * z1 + l32_1 * z2 + l33_1 * z3
  xa2 = true_means2(1) + l11_2 * z1
  xb2 = true_means2(2) + l21_2 * z1 + l22_2 * z2
  xc2 = true_means2(3) + l31_2 * z1 + l32_2 * z2 + l33_2 * z3
  allocate(j_random_1(n))
  call random_number(j_random_1)
  component1 = j_random_1 < true_weight
  xa = merge(1, 0, component1) * xa1 + (1 - merge(1, 0, component1)) * xa2
  xb = merge(1, 0, component1) * xb1 + (1 - merge(1, 0, component1)) * xb2
  xc = merge(1, 0, component1) * xc1 + (1 - merge(1, 0, component1)) * xc2
  ! Start with the empirical mean and covariance, then split along all coordinates.
  ! J: one_fit =: component_update 1 + 0 * xa
  one_fit = component_update(1 + 0 * xa)
  global_mua = one_fit(2)
  global_mub = one_fit(3)
  global_muc = one_fit(4)
  initial_covariance = [real(kind=dp) :: 0.7_dp, 0.7_dp, 0.7_dp, 0, 0, 0]
  two_initial = [real(kind=dp) :: 0.4_dp, [real(kind=dp) :: global_mua - 1.8_dp, [real(kind=dp) :: &
     & global_mub - 1.2_dp, [real(kind=dp) :: global_muc - 0.6_dp, [real(kind=dp) :: &
     & initial_covariance, [real(kind=dp) :: 0.6_dp, [real(kind=dp) :: global_mua + 1.2_dp, &
     & [real(kind=dp) :: global_mub + 0.8_dp, [real(kind=dp) :: global_muc + 0.4_dp, &
     & initial_covariance]]]]]]]]]
  two_fit = fit_two_em(two_initial)
  ! Split component 2 of the fitted two-component model.
  ! J: split_weight =: 0.5 * 10 { two_fit
  split_weight = 0.5_dp * two_fit(11)
  split_scale = sqrt((two_fit(15) + two_fit(16) + two_fit(17)) / 3)
  split_covariance = two_fit([15, 16, 17, 18, 19, 20])
  three_initial = [real(kind=dp) :: two_fit([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), [real(kind=dp) :: &
     & split_weight, [real(kind=dp) :: two_fit(12) - 0.3_dp * split_scale, [real(kind=dp) :: &
     & two_fit(13) - 0.3_dp * split_scale, [real(kind=dp) :: two_fit(14) - 0.3_dp * split_scale, &
     & [real(kind=dp) :: split_covariance, [real(kind=dp) :: split_weight, [real(kind=dp) :: &
     & two_fit(12) + 0.3_dp * split_scale, [real(kind=dp) :: two_fit(13) + 0.3_dp * split_scale, &
     & [real(kind=dp) :: two_fit(14) + 0.3_dp * split_scale, split_covariance]]]]]]]]]]
  three_fit = fit_three_em(three_initial)
  log_likelihoods = [real(kind=dp) :: log_likelihood_one(one_fit), [real(kind=dp) :: &
     & log_likelihood_two(two_fit), log_likelihood_three(three_fit)]]
  ! For k components: k-1 weights and k times (3 means and 6 covariances).
  ! J: parameter_counts =: 9 19 29
  parameter_counts = [9, 19, 29]
  aic = 2 * parameter_counts - 2 * log_likelihoods
  bic = log(real(n, kind=dp)) * parameter_counts - 2 * log_likelihoods
  write (*,"(a)") "dimension and sample size"
  write (*,"(*(i0, 1x))") [dimension_j, n]
  write (*,"(a,1(/,a))") "number of components: 1 2 3", "log likelihood"
  write (*,"(*(g0, 1x))") log_likelihoods
  write (*,"(a)") "AIC"
  write (*,"(*(g0, 1x))") aic
  write (*,"(a)") "BIC"
  write (*,"(*(g0, 1x))") bic
  write (*,"(a)") "components chosen by AIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, aic == minval(aic))))
  write (*,"(a)") "components chosen by BIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, bic == minval(bic))))
  write (*,"(a)") "true covariance matrices are positive definite"
  write (*,"(*(i0, 1x))") merge(1, 0, [covariance_is_pd(true_covariance1), &
     & covariance_is_pd(true_covariance2)])
  write (*,"(a)") "fitted covariance matrices are positive definite"
  write (*,"(*(i0, 1x))") merge(1, 0, [covariance_is_pd(two_fit([5, 6, 7, 8, 9, 10])), &
     & covariance_is_pd(two_fit([15, 16, 17, 18, 19, 20]))])
  write (*,"(a)") "true component 1: mean then covariance entries"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: true_means1, true_covariance1]
  write (*,"(a)") "fitted component 1: weight mean then covariance entries"
  write (*,"(*(g0, 1x))") two_fit([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
  write (*,"(a)") "true component 2: mean then covariance entries"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: true_means2, true_covariance2]
  write (*,"(a)") "fitted component 2: weight mean then covariance entries"
  write (*,"(*(g0, 1x))") two_fit([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
end program fit_mixture_mv_j
