! Generated by xj2f.py 0.1.0 from fit_return_mixture.ijs
! Read asset prices, compute log returns, and fit 1:3 component
! multivariate normal mixtures with unrestricted covariance matrices.

module fit_return_mixture_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: j_component_update, j_fit_em, j_load_returns, j_log_likelihood, j_print_component
  real(kind=dp), parameter :: pi = acos(-1.0_dp)

contains

subroutine j_read_numeric_csv(filename, symbols, values)
  character(len=*), intent(in) :: filename
  character(len=:), allocatable, intent(out) :: symbols(:)
  real(kind=dp), allocatable, intent(out) :: values(:,:)
  character(len=8192) :: line, numeric_line
  character(len=32) :: date_field
  integer :: column, column_count, comma, input_unit, io_status, line_length, row, row_count, start
  open(newunit=input_unit, file=filename, status="old", action="read", iostat=io_status)
  if (io_status /= 0) error stop "cannot open numeric CSV file"
  read(input_unit, "(a)", iostat=io_status) line
  if (io_status /= 0) error stop "numeric CSV file has no header"
  line_length = len_trim(line)
  column_count = 0
  do column = 1, line_length
    if (line(column:column) == ",") column_count = column_count + 1
  end do
  if (column_count < 1) error stop "numeric CSV needs data columns"
  allocate(character(len=32) :: symbols(column_count))
  start = index(line(:line_length), ",") + 1
  do column = 1, column_count
    comma = index(line(start:line_length), ",")
    if (comma == 0) then
      symbols(column) = adjustl(line(start:line_length))
    else
      symbols(column) = adjustl(line(start:start + comma - 2))
      start = start + comma
    end if
  end do
  row_count = 0
  do
    read(input_unit, "(a)", iostat=io_status) line
    if (io_status < 0) exit
    if (io_status > 0) error stop "error reading numeric CSV file"
    if (len_trim(line) > 0) row_count = row_count + 1
  end do
  if (row_count < 2) error stop "numeric CSV needs two data rows"
  rewind(input_unit)
  read(input_unit, "(a)") line
  allocate(values(row_count, column_count))
  row = 0
  do
    read(input_unit, "(a)", iostat=io_status) line
    if (io_status < 0) exit
    if (io_status > 0) error stop "error reading numeric CSV file"
    if (len_trim(line) == 0) cycle
    row = row + 1
    numeric_line = line
    do column = 1, len_trim(numeric_line)
      if (numeric_line(column:column) == ",") numeric_line(column:column) = " "
    end do
    read(numeric_line, *, iostat=io_status) date_field, values(row, :)
    if (io_status /= 0) error stop "invalid numeric CSV data row"
  end do
  close(input_unit)
end subroutine j_read_numeric_csv

pure function j_inverse_real(matrix) result(inverse)
  real(kind=dp), intent(in) :: matrix(:,:)
  real(kind=dp), allocatable :: inverse(:,:)
  real(kind=dp), allocatable :: work(:,:), row_buffer(:)
  real(kind=dp) :: factor, pivot
  integer :: column, matrix_size, pivot_row, row
  matrix_size = size(matrix, 1)
  if (size(matrix, 2) /= matrix_size) error stop "matrix inverse requires a square matrix"
  work = matrix
  allocate(inverse(matrix_size, matrix_size), row_buffer(matrix_size))
  inverse = 0.0_dp
  do row = 1, matrix_size
    inverse(row, row) = 1.0_dp
  end do
  do column = 1, matrix_size
    pivot_row = column - 1 + maxloc(abs(work(column:matrix_size, column)), dim=1)
    pivot = work(pivot_row, column)
    if (abs(pivot) <= tiny(1.0_dp)) error stop "singular matrix"
    if (pivot_row /= column) then
      row_buffer = work(column, :)
      work(column, :) = work(pivot_row, :)
      work(pivot_row, :) = row_buffer
      row_buffer = inverse(column, :)
      inverse(column, :) = inverse(pivot_row, :)
      inverse(pivot_row, :) = row_buffer
    end if
    pivot = work(column, column)
    work(column, :) = work(column, :) / pivot
    inverse(column, :) = inverse(column, :) / pivot
    do row = 1, matrix_size
      if (row == column) cycle
      factor = work(row, column)
      work(row, :) = work(row, :) - factor * work(column, :)
      inverse(row, :) = inverse(row, :) - factor * inverse(column, :)
    end do
  end do
end function j_inverse_real

pure function j_determinant_real(matrix) result(determinant)
  real(kind=dp), intent(in) :: matrix(:,:)
  real(kind=dp) :: determinant
  real(kind=dp), allocatable :: work(:,:), row_buffer(:)
  real(kind=dp) :: factor
  integer :: column, matrix_size, pivot_row, row, sign_factor
  matrix_size = size(matrix, 1)
  if (size(matrix, 2) /= matrix_size) error stop "determinant requires a square matrix"
  work = matrix
  allocate(row_buffer(matrix_size))
  sign_factor = 1
  do column = 1, matrix_size
    pivot_row = column - 1 + maxloc(abs(work(column:matrix_size, column)), dim=1)
    if (abs(work(pivot_row, column)) <= tiny(1.0_dp)) then
      determinant = 0.0_dp
      return
    end if
    if (pivot_row /= column) then
      row_buffer = work(column, :)
      work(column, :) = work(pivot_row, :)
      work(pivot_row, :) = row_buffer
      sign_factor = -sign_factor
    end if
    do row = column + 1, matrix_size
      factor = work(row, column) / work(column, column)
      work(row, column:matrix_size) = &
        work(row, column:matrix_size) - &
        factor * work(column, column:matrix_size)
    end do
  end do
  determinant = real(sign_factor, kind=dp)
  do column = 1, matrix_size
    determinant = determinant * work(column, column)
  end do
end function j_determinant_real

subroutine j_load_returns(filename, symbols, observations)
  character(len=*), intent(in) :: filename
  character(len=:), allocatable, intent(out) :: symbols(:)
  real(kind=dp), allocatable, intent(out) :: observations(:,:)
  real(kind=dp), allocatable :: log_prices(:,:), prices(:,:)
  call j_read_numeric_csv(filename, symbols, prices)
  log_prices = log(prices)
  observations = log_prices(2:, :) - log_prices(:size(log_prices, 1) - 1, :)
end subroutine j_load_returns

pure function j_mv_density(observations, mean_vector, covariance) result(density)
  real(kind=dp), intent(in) :: observations(:,:), mean_vector(:), covariance(:,:)
  real(kind=dp), allocatable :: density(:)
  real(kind=dp), allocatable :: centered(:,:), inverse(:,:), quadratic(:)
  real(kind=dp) :: determinant, normalizer
  integer :: dimension_j
  dimension_j = size(observations, 2)
  centered = observations - spread(mean_vector, dim=1, ncopies=size(observations, 1))
  inverse = j_inverse_real(covariance)
  quadratic = sum(matmul(centered, inverse) * centered, dim=2)
  determinant = max(1.0e-300_dp, j_determinant_real(covariance))
  normalizer = (2.0_dp * pi)**(0.5_dp * dimension_j) * sqrt(determinant)
  density = max(1.0e-300_dp, exp(-0.5_dp * quadratic) / normalizer)
end function j_mv_density

pure subroutine j_component_update(observations, responsibilities, &
    component_weight, mean_vector, covariance)
  real(kind=dp), intent(in) :: observations(:,:), responsibilities(:)
  real(kind=dp), intent(out) :: component_weight, mean_vector(:), covariance(:,:)
  real(kind=dp), allocatable :: centered(:,:), weighted_centered(:,:)
  real(kind=dp) :: average_variance, ridge, weight_sum
  integer :: asset, dimension_j, observation_count
  observation_count = size(observations, 1)
  dimension_j = size(observations, 2)
  weight_sum = max(1.0e-12_dp, sum(responsibilities))
  component_weight = weight_sum / observation_count
  mean_vector = matmul(responsibilities, observations) / weight_sum
  centered = observations - spread(mean_vector, dim=1, ncopies=observation_count)
  weighted_centered = centered * spread(responsibilities, dim=2, ncopies=dimension_j)
  covariance = matmul(transpose(centered), weighted_centered) / weight_sum
  average_variance = 0.0_dp
  do asset = 1, dimension_j
    average_variance = average_variance + covariance(asset, asset)
  end do
  average_variance = average_variance / dimension_j
  ridge = max(1.0e-10_dp, 1.0e-6_dp * average_variance)
  do asset = 1, dimension_j
    covariance(asset, asset) = covariance(asset, asset) + ridge
  end do
end subroutine j_component_update

pure subroutine j_fit_em(observations, max_iterations, weights, means, covariances)
  real(kind=dp), intent(in) :: observations(:,:)
  integer, intent(in) :: max_iterations
  real(kind=dp), intent(inout) :: weights(:), means(:,:), covariances(:,:,:)
  real(kind=dp), parameter :: convergence_tolerance = 1.0e-9_dp
  real(kind=dp), allocatable :: total_density(:), weighted_density(:,:)
  real(kind=dp) :: current_log_likelihood, previous_log_likelihood
  integer :: component, component_count, dimension_j, iteration, observation_count
  observation_count = size(observations, 1)
  dimension_j = size(observations, 2)
  component_count = size(weights)
  allocate(weighted_density(observation_count, component_count), total_density(observation_count))
  previous_log_likelihood = j_log_likelihood(observations, weights, means, covariances)
  do iteration = 1, max_iterations
    do component = 1, component_count
      weighted_density(:, component) = weights(component) * &
        j_mv_density(observations, means(:, component), &
                     covariances(:, :, component))
    end do
    total_density = max(1.0e-300_dp, sum(weighted_density, dim=2))
    do component = 1, component_count
      call j_component_update(observations, &
        weighted_density(:, component) / total_density, &
        weights(component), means(:, component), &
        covariances(:, :, component))
    end do
    current_log_likelihood = j_log_likelihood(observations, weights, means, covariances)
    if (abs(current_log_likelihood - previous_log_likelihood) <= &
        convergence_tolerance * &
        (1.0_dp + abs(previous_log_likelihood))) exit
    previous_log_likelihood = current_log_likelihood
  end do
end subroutine j_fit_em

pure function j_log_likelihood(observations, weights, means, covariances) result(log_likelihood)
  real(kind=dp), intent(in) :: observations(:,:), weights(:), means(:,:), covariances(:,:,:)
  real(kind=dp) :: log_likelihood
  real(kind=dp), allocatable :: total_density(:)
  integer :: component
  allocate(total_density(size(observations, 1)))
  total_density = 0.0_dp
  do component = 1, size(weights)
    total_density = total_density + weights(component) * &
      j_mv_density(observations, means(:, component), &
                   covariances(:, :, component))
  end do
  log_likelihood = sum(log(max(1.0e-300_dp, total_density)))
end function j_log_likelihood

subroutine j_print_component(component, symbols, trading_days, weight, mean_vector, covariance)
  integer, intent(in) :: component, trading_days
  character(len=*), intent(in) :: symbols(:)
  real(kind=dp), intent(in) :: weight, mean_vector(:), covariance(:,:)
  real(kind=dp) :: annual_mean, annual_volatility
  integer :: asset
  write (*,"(a,i0,a)") "component ", component, " weight"
  write (*,"(f8.6)") weight
  write (*,"(a6,2(1x,a21))") "symbol", "annualized mean", "annualized volatility"
  do asset = 1, size(symbols)
    annual_mean = trading_days * mean_vector(asset)
    annual_volatility = sqrt(real(trading_days, kind=dp)) * sqrt(covariance(asset, asset))
    write (*,"(a6,2(1x,f21.6))") trim(symbols(asset)), annual_mean, annual_volatility
  end do
end subroutine j_print_component

end module fit_return_mixture_j_mod

program fit_return_mixture_j
  use fit_return_mixture_j_mod, only: j_component_update, j_fit_em, &
    j_load_returns, j_log_likelihood, j_print_component
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  character(len=:), allocatable :: symbols(:)
  real(kind=dp), allocatable :: covariances1(:,:,:), covariances2(:,:,:), covariances3(:,:,:), &
     & means1(:,:), means2(:,:), means3(:,:), observations(:,:), responsibilities(:), weights1(:), &
     & weights2(:), weights3(:)
  real(kind=dp) :: aic(3), bic(3), log_likelihoods(3), split_weight
  integer, parameter :: trading_days = 252
  integer :: aic_components, asset, bic_components, dimension_j, model, observation_count, &
     & parameter_counts(3), parameters_per_component
  call j_load_returns("asset_class_etf_prices.csv", symbols, observations)
  observation_count = size(observations, 1)
  dimension_j = size(observations, 2)
  allocate(responsibilities(observation_count), &
     & weights1(1), &
     & means1(dimension_j, 1), &
     & covariances1(dimension_j, dimension_j, 1))
  responsibilities = 1.0_dp
  call j_component_update(observations, responsibilities, weights1(1), &
    means1(:, 1), covariances1(:, :, 1))

  allocate(means2(dimension_j, 2), covariances2(dimension_j, dimension_j, 2))
  weights2 = [0.7_dp, 0.3_dp]
  means2(:, 1) = means1(:, 1)
  means2(:, 2) = means1(:, 1)
  covariances2(:, :, 1) = 0.6_dp * covariances1(:, :, 1)
  covariances2(:, :, 2) = 2.0_dp * covariances1(:, :, 1)
  call j_fit_em(observations, 300, weights2, means2, covariances2)

  allocate(means3(dimension_j, 3), covariances3(dimension_j, dimension_j, 3))
  split_weight = 0.5_dp * weights2(2)
  weights3 = [weights2(1), split_weight, split_weight]
  means3(:, 1) = means2(:, 1)
  means3(:, 2) = means2(:, 2)
  means3(:, 3) = means2(:, 2)
  covariances3(:, :, 1) = covariances2(:, :, 1)
  covariances3(:, :, 2) = 0.7_dp * covariances2(:, :, 2)
  covariances3(:, :, 3) = 1.3_dp * covariances2(:, :, 2)
  call j_fit_em(observations, 400, weights3, means3, covariances3)

  log_likelihoods(1) = j_log_likelihood(observations, weights1, means1, covariances1)
  log_likelihoods(2) = j_log_likelihood(observations, weights2, means2, covariances2)
  log_likelihoods(3) = j_log_likelihood(observations, weights3, means3, covariances3)
  parameters_per_component = dimension_j + dimension_j * (dimension_j + 1) / 2
  do model = 1, 3
    parameter_counts(model) = model * parameters_per_component + model - 1
  end do
  aic = 2.0_dp * parameter_counts - 2.0_dp * log_likelihoods
  bic = log(real(observation_count, kind=dp)) * parameter_counts - 2.0_dp * log_likelihoods
  aic_components = minloc(aic, dim=1)
  bic_components = minloc(bic, dim=1)

  write (*,"(a,2(/,a))") "price file", "asset_class_etf_prices.csv", "assets"
  write (*,"(*(a,1x))") (trim(symbols(asset)), asset = 1, dimension_j)
  write (*,"(a)") "return observations and dimension"
  write (*,"(2(i0,1x))") observation_count, dimension_j
  write (*,"(a)") "model comparison"
  write (*,"(a10,3(1x,a18))") "components", "log likelihood", "AIC", "BIC"
  do model = 1, 3
    write (*,"(i10,3(1x,f18.6))") model, log_likelihoods(model), aic(model), bic(model)
  end do
  write (*,"(a,i0)") "components chosen by AIC: ", aic_components, &
                     "components chosen by BIC: ", bic_components, &
                     "two-component fit"
  do model = 1, 2
    call j_print_component(model, symbols, trading_days, weights2(model), &
      means2(:, model), covariances2(:, :, model))
  end do
  write (*,"(a)") "three-component fit"
  do model = 1, 3
    call j_print_component(model, symbols, trading_days, weights3(model), &
      means3(:, model), covariances3(:, :, model))
  end do
end program fit_return_mixture_j
