! Generated by xj2f.py 0.1.0 from fit_mixture_ic.ijs
! Fit one, two, and three normal components and compare AIC and BIC.

module fit_mixture_ic_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: mean, mixture_moments, moment_jacobian, fit_mixture_moments, fit_two_em, fit_three_em, &
     & log_likelihood_one, log_likelihood_two, log_likelihood_three, pi, x, sample_moments, &
     & moment_scale, normal_constant, j_iota
  real(kind=dp), parameter :: pi = acos(-1.0_dp)
  real(kind=dp), allocatable :: x(:), sample_moments(:), moment_scale(:)
  real(kind=dp) :: normal_constant

contains

pure function mean(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(y) / size(y, 1)
end function mean

! Moment matching initializes the two-component EM fit.
! J: mixture_moments =: 3 : 0
pure function mixture_moments(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp) :: mu1, sd1, mu2, sd2, weight
  real(kind=dp), allocatable :: component1_moments(:), component2_moments(:)
  mu1 = y(2)
  sd1 = exp(y(3))
  mu2 = y(4)
  sd2 = exp(y(5))
  weight = 1.0_dp / (1 + exp(-y(1)))
  component1_moments = [real(kind=dp) :: mu1, [real(kind=dp) :: mu1**2 + sd1**2, [real(kind=dp) :: &
     & mu1**3 + 3 * mu1 * sd1**2, [real(kind=dp) :: mu1**4 + 6 * mu1**2 * sd1**2 + 3 * sd1**4, &
     & mu1**5 + 10 * mu1**3 * sd1**2 + 15 * mu1 * sd1**4]]]]
  component2_moments = [real(kind=dp) :: mu2, [real(kind=dp) :: mu2**2 + sd2**2, [real(kind=dp) :: &
     & mu2**3 + 3 * mu2 * sd2**2, [real(kind=dp) :: mu2**4 + 6 * mu2**2 * sd2**2 + 3 * sd2**4, &
     & mu2**5 + 10 * mu2**3 * sd2**2 + 15 * mu2 * sd2**4]]]]
  j_result = weight * component1_moments + (1 - weight) * component2_moments
end function mixture_moments

pure function moment_jacobian(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:,:)
  real(kind=dp) :: step_size
  real(kind=dp), allocatable :: base(:), jacobian(:,:), shifted(:), column(:)
  integer :: parameter_j
  step_size = 1e-5_dp
  base = mixture_moments(y)
  jacobian = reshape([0.0_dp], [5, 5], pad=[0.0_dp], order=[2, 1])
  do parameter_j = 0, 5 - 1
    shifted = y + step_size * (merge(1, 0, parameter_j == j_iota(5)))
    column = (mixture_moments(shifted) - base) / (step_size * moment_scale)
    jacobian = jacobian + spread(column, dim=2, ncopies=size(merge(1, 0, &
       & parameter_j == j_iota(5)))) * spread(merge(1, 0, parameter_j == j_iota(5)), dim=1, &
       & ncopies=size(column))
  end do
  j_result = jacobian
end function moment_jacobian

pure function fit_mixture_moments(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), residual(:), jacobian(:,:), normal_matrix(:,:), &
     & normal_rhs(:), update(:)
  logical, allocatable :: identity(:,:)
  real(kind=dp) :: damping
  integer :: iteration
  parameters = y
  identity = spread(j_iota(5), dim=2, ncopies=size(j_iota(5))) == spread(j_iota(5), dim=1, &
     & ncopies=size(j_iota(5)))
  damping = 0.01_dp
  do iteration = 0, 100 - 1
    residual = (sample_moments - mixture_moments(parameters)) / moment_scale
    jacobian = moment_jacobian(parameters)
    normal_matrix = matmul(transpose(jacobian), jacobian) + damping * merge(1, 0, identity)
    normal_rhs = matmul(transpose(jacobian), residual)
    update = j_solve_real_vector(normal_rhs, normal_matrix)
    parameters = parameters + update
    if (1e-9_dp > maxval(abs(update))) then
      exit
    end if
  end do
  j_result = parameters
end function fit_mixture_moments

! Natural parameters are weight, mu1, sd1, mu2, sd2.
! J: fit_two_em =: 3 : 0
pure function fit_two_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), density1(:), density2(:), weighted1(:), weighted2(: &
     & ), responsibility(:), other_responsibility(:), new_parameters(:)
  integer :: iteration
  real(kind=dp) :: weight, mu1, sd1, mu2, sd2, responsibility_sum, other_sum, new_weight, new_mu1, &
     & new_mu2, new_sd1, new_sd2
  parameters = y
  do iteration = 0, 200 - 1
    weight = parameters(1)
    mu1 = parameters(2)
    sd1 = parameters(3)
    mu2 = parameters(4)
    sd2 = parameters(5)
    density1 = exp(-0.5_dp * ((x - mu1) / sd1)**2) / (normal_constant * sd1)
    density2 = exp(-0.5_dp * ((x - mu2) / sd2)**2) / (normal_constant * sd2)
    weighted1 = weight * density1
    weighted2 = (1 - weight) * density2
    responsibility = weighted1 / (max(1e-300_dp, weighted1 + weighted2))
    other_responsibility = 1 - responsibility
    responsibility_sum = sum(responsibility)
    other_sum = sum(other_responsibility)
    new_weight = mean(responsibility)
    new_mu1 = sum(responsibility * x) / responsibility_sum
    new_mu2 = sum(other_responsibility * x) / other_sum
    new_sd1 = max(1e-8_dp, sqrt(sum(responsibility * (x - new_mu1)**2) / responsibility_sum))
    new_sd2 = max(1e-8_dp, sqrt(sum(other_responsibility * (x - new_mu2)**2) / other_sum))
    new_parameters = [real(kind=dp) :: new_weight, [real(kind=dp) :: new_mu1, [real(kind=dp) :: &
       & new_sd1, [real(kind=dp) :: new_mu2, new_sd2]]]]
    if (1e-9_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_two_em

! Three-component parameters are weights, means, then standard deviations.
! J: fit_three_em =: 3 : 0
pure function fit_three_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), density1(:), density2(:), density3(:), weighted1(:) &
     & , weighted2(:), weighted3(:), total_density(:), responsibility1(:), responsibility2(:), &
     & responsibility3(:), new_parameters(:)
  integer :: iteration
  real(kind=dp) :: weight1, weight2, weight3, mu1, mu2, mu3, sd1, sd2, sd3, sum1, sum2, sum3, &
     & new_weight1, new_weight2, new_weight3, new_mu1, new_mu2, new_mu3, new_sd1, new_sd2, new_sd3
  parameters = y
  do iteration = 0, 300 - 1
    weight1 = parameters(1)
    weight2 = parameters(2)
    weight3 = parameters(3)
    mu1 = parameters(4)
    mu2 = parameters(5)
    mu3 = parameters(6)
    sd1 = parameters(7)
    sd2 = parameters(8)
    sd3 = parameters(9)
    density1 = exp(-0.5_dp * ((x - mu1) / sd1)**2) / (normal_constant * sd1)
    density2 = exp(-0.5_dp * ((x - mu2) / sd2)**2) / (normal_constant * sd2)
    density3 = exp(-0.5_dp * ((x - mu3) / sd3)**2) / (normal_constant * sd3)
    weighted1 = weight1 * density1
    weighted2 = weight2 * density2
    weighted3 = weight3 * density3
    total_density = max(1e-300_dp, weighted1 + weighted2 + weighted3)
    responsibility1 = weighted1 / total_density
    responsibility2 = weighted2 / total_density
    responsibility3 = weighted3 / total_density
    sum1 = sum(responsibility1)
    sum2 = sum(responsibility2)
    sum3 = sum(responsibility3)
    new_weight1 = mean(responsibility1)
    new_weight2 = mean(responsibility2)
    new_weight3 = mean(responsibility3)
    new_mu1 = sum(responsibility1 * x) / sum1
    new_mu2 = sum(responsibility2 * x) / sum2
    new_mu3 = sum(responsibility3 * x) / sum3
    new_sd1 = max(1e-8_dp, sqrt(sum(responsibility1 * (x - new_mu1)**2) / sum1))
    new_sd2 = max(1e-8_dp, sqrt(sum(responsibility2 * (x - new_mu2)**2) / sum2))
    new_sd3 = max(1e-8_dp, sqrt(sum(responsibility3 * (x - new_mu3)**2) / sum3))
    new_parameters = [real(kind=dp) :: new_weight1, [real(kind=dp) :: new_weight2, [real(kind=dp) &
       & :: new_weight3, [real(kind=dp) :: new_mu1, [real(kind=dp) :: new_mu2, [real(kind=dp) :: &
       & new_mu3, [real(kind=dp) :: new_sd1, [real(kind=dp) :: new_sd2, new_sd3]]]]]]]]
    if (1e-9_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_three_em

pure function log_likelihood_one(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp) :: sd
  sd = y(2)
  j_result = sum(log(max(1e-300_dp, (exp(-0.5_dp * ((x - y(1)) / sd)**2) / (normal_constant * sd)) &
     & )))
end function log_likelihood_one

pure function log_likelihood_two(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp) :: weight, sd1, sd2
  real(kind=dp), allocatable :: density1(:), density2(:)
  weight = y(1)
  sd1 = y(3)
  sd2 = y(5)
  density1 = exp(-0.5_dp * ((x - y(2)) / sd1)**2) / (normal_constant * sd1)
  density2 = exp(-0.5_dp * ((x - y(4)) / sd2)**2) / (normal_constant * sd2)
  j_result = sum(log(max(1e-300_dp, weight * density1 + (1 - weight) * density2)))
end function log_likelihood_two

pure function log_likelihood_three(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp) :: sd1, sd2, sd3
  real(kind=dp), allocatable :: density1(:), density2(:), density3(:)
  sd1 = y(7)
  sd2 = y(8)
  sd3 = y(9)
  density1 = exp(-0.5_dp * ((x - y(4)) / sd1)**2) / (normal_constant * sd1)
  density2 = exp(-0.5_dp * ((x - y(5)) / sd2)**2) / (normal_constant * sd2)
  density3 = exp(-0.5_dp * ((x - y(6)) / sd3)**2) / (normal_constant * sd3)
  j_result = sum(log(max(1e-300_dp, y(1) * density1 + y(2) * density2 + y(3) * density3)))
end function log_likelihood_three

pure function j_multiplication_table_int(left, right) result(table_values)
  integer, intent(in) :: left(:), right(:)
  integer, allocatable :: table_values(:,:)
  integer :: row_index
  allocate(table_values(size(left), size(right)))
  do row_index = 1, size(left)
    table_values(row_index, :) = left(row_index) * right
  end do
end function j_multiplication_table_int

pure function j_solve_real_vector(rhs, coefficients) result(solution)
  real(kind=dp), intent(in) :: rhs(:), coefficients(:,:)
  real(kind=dp), allocatable :: solution(:)
  real(kind=dp), allocatable :: work(:,:), work_rhs(:), row_buffer(:)
  real(kind=dp) :: factor, scalar_buffer
  integer :: column, row, pivot_row, system_size
  system_size = size(rhs)
  if (size(coefficients, 1) /= system_size .or. &
      size(coefficients, 2) /= system_size) &
    error stop "linear solve shape mismatch"
  work = coefficients
  work_rhs = rhs
  allocate(solution(system_size), row_buffer(system_size))
  do column = 1, system_size
    pivot_row = column - 1 + maxloc(abs(work(column:system_size, column)), dim=1)
    if (abs(work(pivot_row, column)) <= tiny(1.0_dp)) error stop "singular matrix"
    if (pivot_row /= column) then
      row_buffer = work(column, :)
      work(column, :) = work(pivot_row, :)
      work(pivot_row, :) = row_buffer
      scalar_buffer = work_rhs(column)
      work_rhs(column) = work_rhs(pivot_row)
      work_rhs(pivot_row) = scalar_buffer
    end if
    do row = column + 1, system_size
      factor = work(row, column) / work(column, column)
      work(row, column:system_size) = work(row, column:system_size) - &
        factor * work(column, column:system_size)
      work_rhs(row) = work_rhs(row) - factor * work_rhs(column)
    end do
  end do
  do row = system_size, 1, -1
    solution(row) = work_rhs(row)
    if (row < system_size) solution(row) = solution(row) - &
      dot_product(work(row, row + 1:system_size), &
                  solution(row + 1:system_size))
    solution(row) = solution(row) / work(row, row)
  end do
end function j_solve_real_vector

pure function j_iota(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:)
  integer :: value_index
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n))
  do value_index = 1, n
    values(value_index) = value_index - 1
  end do
end function j_iota

end module fit_mixture_ic_j_mod

program fit_mixture_ic_j
  use fit_mixture_ic_j_mod, only: fit_mixture_moments, fit_three_em, fit_two_em, j_iota, &
     & log_likelihood_one, log_likelihood_three, log_likelihood_two, mean, mixture_moments, &
     & moment_jacobian, moment_scale, normal_constant, pi, sample_moments, x
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer :: n, true_mu1, true_mu2
  real(kind=dp) :: true_weight, true_sd1, true_sd2, one_mu, one_sd, split_weight, split_mu, split_sd
  real(kind=dp), allocatable :: u1(:), u2(:), z1(:), u3(:), u4(:), z2(:), x1(:), x2(:), one_fit(:) &
     & , moment_initial(:), moment_internal(:), two_initial(:), two_fit(:), three_initial(:), &
     & three_fit(:), log_likelihoods(:), aic(:), bic(:)
  logical, allocatable :: component1(:)
  integer, allocatable :: parameter_counts(:)
  real(kind=dp), allocatable :: j_random_1(:)
  n = 200000
  ! Parameters used to generate a two-component sample.
  ! J: true_weight =: 0.35
  true_weight = 0.35_dp
  true_mu1 = -1
  true_sd1 = 0.8_dp
  true_mu2 = 2
  true_sd2 = 1.3_dp
  ! Generate two independent standard normal samples by Box-Muller.
  ! J: u1 =: 1e_12 >. ? n $ 0
  allocate(u1(n), u2(n))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  z1 = sqrt(-2 * log(u1)) * cos(2 * pi * u2)
  allocate(u3(n), u4(n))
  call random_number(u3)
  u3 = max(1e-12_dp, u3)
  call random_number(u4)
  z2 = sqrt(-2 * log(u3)) * cos(2 * pi * u4)
  allocate(j_random_1(n))
  call random_number(j_random_1)
  component1 = j_random_1 < true_weight
  x1 = true_mu1 + true_sd1 * z1
  x2 = true_mu2 + true_sd2 * z2
  x = merge(1, 0, component1) * x1 + (1 - merge(1, 0, component1)) * x2
  sample_moments = [real(kind=dp) :: mean(x), [real(kind=dp) :: mean(x**2), [real(kind=dp) :: &
     & mean(x**3), [real(kind=dp) :: mean(x**4), mean(x**5)]]]]
  moment_scale = max(1.0_dp, abs(sample_moments))
  normal_constant = sqrt(2 * pi)
  ! Fit one component directly and two components from matched moments.
  ! J: one_mu =: mean x
  one_mu = mean(x)
  one_sd = sqrt(mean((x - one_mu)**2))
  one_fit = [real(kind=dp) :: one_mu, one_sd]
  moment_initial = [-0.4_dp, -0.7_dp, -0.1_dp, 1.7_dp, 0.1_dp]
  moment_internal = fit_mixture_moments(moment_initial)
  two_initial = [real(kind=dp) :: 1.0_dp / (1 + exp(-moment_internal(1))), [real(kind=dp) :: &
     & moment_internal(2), [real(kind=dp) :: exp(moment_internal(3)), [real(kind=dp) :: &
     & moment_internal(4), exp(moment_internal(5))]]]]
  two_fit = fit_two_em(two_initial)
  ! Initialize three components by splitting component 2 of the two-component fit.
  ! J: split_weight =: 0.5 * 1 - 0 { two_fit
  split_weight = 0.5_dp * 1 - two_fit(1)
  split_mu = two_fit(4)
  split_sd = two_fit(5)
  three_initial = [real(kind=dp) :: two_fit(1), [real(kind=dp) :: split_weight, [real(kind=dp) :: &
     & split_weight, [real(kind=dp) :: two_fit(2), [real(kind=dp) :: split_mu - 0.5_dp * split_sd, &
     & [real(kind=dp) :: split_mu + 0.5_dp * split_sd, [real(kind=dp) :: two_fit(3), [real(kind=dp &
     & ) :: split_sd, split_sd]]]]]]]]
  three_fit = fit_three_em(three_initial)
  log_likelihoods = [real(kind=dp) :: log_likelihood_one(one_fit), [real(kind=dp) :: &
     & log_likelihood_two(two_fit), log_likelihood_three(three_fit)]]
  parameter_counts = [2, 5, 8]
  aic = 2 * parameter_counts - 2 * log_likelihoods
  bic = log(real(n, kind=dp)) * parameter_counts - 2 * log_likelihoods
  write (*,"(a,1(/,a))") "number of components: 1 2 3", "log likelihood"
  write (*,"(*(g0, 1x))") log_likelihoods
  write (*,"(a)") "AIC"
  write (*,"(*(g0, 1x))") aic
  write (*,"(a)") "BIC"
  write (*,"(*(g0, 1x))") bic
  write (*,"(a)") "components chosen by AIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, aic == minval(aic))))
  write (*,"(a)") "components chosen by BIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, bic == minval(bic))))
  write (*,"(a)") "two-component estimate: weight mu1 sd1 mu2 sd2"
  write (*,"(*(g0, 1x))") two_fit
  write (*,"(a)") "three-component estimate: weights means standard deviations"
  write (*,"(*(g0, 1x))") three_fit
end program fit_mixture_ic_j
