! Generated by xj2f.py 0.1.0 from fit_mixture_eqc.ijs
! Simulate and fit 3-dimensional normal mixtures with equicorrelation.

module fit_mixture_eqc_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: eqc_density, component_update, fit_two_em, fit_three_em, log_likelihood_one, &
     & log_likelihood_two, log_likelihood_three, pi, n, xa, xb, xc, j_iota
  real(kind=dp), parameter :: pi = acos(-1.0_dp)
  integer :: n
  real(kind=dp), allocatable :: xa(:), xb(:), xc(:)

contains

! y contains three means, a common sigma, and the equicorrelation rho.
! J: eqc_density =: 3 : 0
pure function eqc_density(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp) :: sigma, rho
  real(kind=dp), allocatable :: za(:), zb(:), zc(:), quadratic(:)
  sigma = y(4)
  rho = y(5)
  za = (xa - y(1)) / sigma
  zb = (xb - y(2)) / sigma
  zc = (xc - y(3)) / sigma
  quadratic = ((za**2 + zb**2 + zc**2) - rho / (1 + 2 * rho) * ((za + zb + zc)**2)) / (1 - rho)
  j_result = exp(-0.5_dp * quadratic) / (15.7496099457_dp * sigma**3 * sqrt(((1 - rho)**2 * (1 + 2 &
     & * rho))))
end function eqc_density

! One weighted M-step returns weight, three means, sigma, and rho.
! J: component_update =: 3 : 0
pure function component_update(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: responsibility(:), da(:), db(:), dc(:)
  real(kind=dp) :: responsibility_sum, weight, mua, mub, muc, diagonal, off_diagonal, sigma, rho
  responsibility = y
  responsibility_sum = sum(responsibility)
  weight = responsibility_sum / n
  mua = sum(responsibility * xa) / responsibility_sum
  mub = sum(responsibility * xb) / responsibility_sum
  muc = sum(responsibility * xc) / responsibility_sum
  da = xa - mua
  db = xb - mub
  dc = xc - muc
  diagonal = sum(responsibility * (da**2 + db**2 + dc**2)) / (3 * responsibility_sum)
  off_diagonal = sum(responsibility * (da * db + da * dc + db * dc)) / (3 * responsibility_sum)
  sigma = max(1e-8_dp, sqrt(diagonal))
  rho = max(-0.49_dp, min(0.95_dp, off_diagonal / diagonal))
  j_result = [real(kind=dp) :: weight, [real(kind=dp) :: mua, [real(kind=dp) :: mub, [real(kind=dp &
     & ) :: muc, [real(kind=dp) :: sigma, rho]]]]]
end function component_update

pure function fit_two_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), component1_parameters(:), component2_parameters(:), &
     & density1(:), density2(:), weighted1(:), weighted2(:), total_density(:), update1(:), &
     & update2(:), new_parameters(:)
  integer :: iteration
  real(kind=dp) :: weight1, weight2
  parameters = y
  do iteration = 0, 200 - 1
    weight1 = parameters(1)
    weight2 = parameters(7)
    component1_parameters = parameters([2, 3, 4, 5, 6])
    component2_parameters = parameters([8, 9, 10, 11, 12])
    density1 = eqc_density(component1_parameters)
    density2 = eqc_density(component2_parameters)
    weighted1 = weight1 * density1
    weighted2 = weight2 * density2
    total_density = max(1e-300_dp, weighted1 + weighted2)
    update1 = component_update(weighted1 / total_density)
    update2 = component_update(weighted2 / total_density)
    new_parameters = [real(kind=dp) :: update1, update2]
    if (1e-8_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_two_em

pure function fit_three_em(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp), allocatable :: j_result(:)
  real(kind=dp), allocatable :: parameters(:), component1_parameters(:), component2_parameters(:), &
     & component3_parameters(:), density1(:), density2(:), density3(:), weighted1(:), weighted2(:) &
     & , weighted3(:), total_density(:), update1(:), update2(:), update3(:), new_parameters(:)
  integer :: iteration
  real(kind=dp) :: weight1, weight2, weight3
  parameters = y
  do iteration = 0, 250 - 1
    weight1 = parameters(1)
    weight2 = parameters(7)
    weight3 = parameters(13)
    component1_parameters = parameters([2, 3, 4, 5, 6])
    component2_parameters = parameters([8, 9, 10, 11, 12])
    component3_parameters = parameters([14, 15, 16, 17, 18])
    density1 = eqc_density(component1_parameters)
    density2 = eqc_density(component2_parameters)
    density3 = eqc_density(component3_parameters)
    weighted1 = weight1 * density1
    weighted2 = weight2 * density2
    weighted3 = weight3 * density3
    total_density = max(1e-300_dp, weighted1 + weighted2 + weighted3)
    update1 = component_update(weighted1 / total_density)
    update2 = component_update(weighted2 / total_density)
    update3 = component_update(weighted3 / total_density)
    new_parameters = [real(kind=dp) :: update1, [real(kind=dp) :: update2, update3]]
    if (1e-8_dp > maxval(abs(new_parameters - parameters))) then
      parameters = new_parameters
      exit
    end if
    parameters = new_parameters
  end do
  j_result = parameters
end function fit_three_em

pure function log_likelihood_one(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(log(max(1e-300_dp, (eqc_density(y([2, 3, 4, 5, 6]))))))
end function log_likelihood_one

pure function log_likelihood_two(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp), allocatable :: density2(:)
  density2 = y(7) * eqc_density(y([8, 9, 10, 11, 12]))
  j_result = sum(log(max(1e-300_dp, (y(1) * eqc_density(y([2, 3, 4, 5, 6]))) + density2)))
end function log_likelihood_two

pure function log_likelihood_three(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  real(kind=dp), allocatable :: density2(:), density3(:)
  density2 = y(7) * eqc_density(y([8, 9, 10, 11, 12]))
  density3 = y(13) * eqc_density(y([14, 15, 16, 17, 18]))
  j_result = sum(log(max(1e-300_dp, (y(1) * eqc_density(y([2, 3, 4, 5, 6]))) + density2 + density3 &
     & )))
end function log_likelihood_three

pure function j_iota(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:)
  integer :: value_index
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n))
  do value_index = 1, n
    values(value_index) = value_index - 1
  end do
end function j_iota

end module fit_mixture_eqc_j_mod

program fit_mixture_eqc_j
  use fit_mixture_eqc_j_mod, only: component_update, eqc_density, fit_three_em, fit_two_em, j_iota &
     & , log_likelihood_one, log_likelihood_three, log_likelihood_two, n, pi, xa, xb, xc
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer :: dimension_j
  real(kind=dp) :: true_weight, true_sigma1, true_rho1, true_sigma2, true_rho2, common1, &
     & independent1, common2, independent2, global_mua, global_mub, global_muc, global_sigma, &
     & split_weight, split_sigma
  real(kind=dp), allocatable :: true_means1(:), true_means2(:), u1(:), u2(:), z0(:), u3(:), u4(:), &
     & z1(:), u5(:), u6(:), z2(:), u7(:), u8(:), z3(:), xa1(:), xb1(:), xc1(:), xa2(:), xb2(:), &
     & xc2(:), one_fit(:), two_initial(:), two_fit(:), three_initial(:), three_fit(:), &
     & log_likelihoods(:), aic(:), bic(:)
  logical, allocatable :: component1(:)
  integer, allocatable :: parameter_counts(:)
  real(kind=dp), allocatable :: j_random_1(:)
  n = 50000
  dimension_j = 3
  ! The sample comes from a two-component equicorrelated normal mixture.
  ! J: true_weight =: 0.4
  true_weight = 0.4_dp
  true_means1 = [real(kind=dp) :: -1, -0.5_dp, 0]
  true_sigma1 = 0.8_dp
  true_rho1 = 0.35_dp
  true_means2 = [real(kind=dp) :: 2, 1.5_dp, 1]
  true_sigma2 = 1.2_dp
  true_rho2 = 0.6_dp
  ! Four independent standard normal vectors are enough for a common-factor model.
  ! J: u1 =: 1e_12 >. ? n $ 0
  allocate(u1(n), u2(n))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  z0 = sqrt(-2 * log(u1)) * cos(2 * pi * u2)
  allocate(u3(n), u4(n))
  call random_number(u3)
  u3 = max(1e-12_dp, u3)
  call random_number(u4)
  z1 = sqrt(-2 * log(u3)) * cos(2 * pi * u4)
  allocate(u5(n), u6(n))
  call random_number(u5)
  u5 = max(1e-12_dp, u5)
  call random_number(u6)
  z2 = sqrt(-2 * log(u5)) * cos(2 * pi * u6)
  allocate(u7(n), u8(n))
  call random_number(u7)
  u7 = max(1e-12_dp, u7)
  call random_number(u8)
  z3 = sqrt(-2 * log(u7)) * cos(2 * pi * u8)
  ! A common factor gives every pair of coordinates correlation rho.
  ! J: common1 =: %: true_rho1
  common1 = sqrt(true_rho1)
  independent1 = sqrt(1 - true_rho1)
  xa1 = true_means1(1) + true_sigma1 * (common1 * z0 + independent1 * z1)
  xb1 = true_means1(2) + true_sigma1 * (common1 * z0 + independent1 * z2)
  xc1 = true_means1(3) + true_sigma1 * (common1 * z0 + independent1 * z3)
  common2 = sqrt(true_rho2)
  independent2 = sqrt(1 - true_rho2)
  xa2 = true_means2(1) + true_sigma2 * (common2 * z0 + independent2 * z1)
  xb2 = true_means2(2) + true_sigma2 * (common2 * z0 + independent2 * z2)
  xc2 = true_means2(3) + true_sigma2 * (common2 * z0 + independent2 * z3)
  allocate(j_random_1(n))
  call random_number(j_random_1)
  component1 = j_random_1 < true_weight
  xa = merge(1, 0, component1) * xa1 + (1 - merge(1, 0, component1)) * xa2
  xb = merge(1, 0, component1) * xb1 + (1 - merge(1, 0, component1)) * xb2
  xc = merge(1, 0, component1) * xc1 + (1 - merge(1, 0, component1)) * xc2
  ! The one-component M-step also supplies scale information for initialization.
  ! J: one_fit =: component_update 1 + 0 * xa
  one_fit = component_update(1 + 0 * xa)
  global_mua = one_fit(2)
  global_mub = one_fit(3)
  global_muc = one_fit(4)
  global_sigma = one_fit(5)
  two_initial = [real(kind=dp) :: 0.5_dp, [real(kind=dp) :: global_mua - 0.75_dp * global_sigma, &
     & [real(kind=dp) :: global_mub - 0.75_dp * global_sigma, [real(kind=dp) :: global_muc - &
     & 0.75_dp * global_sigma, [real(kind=dp) :: global_sigma, [real(kind=dp) :: 0.2_dp, &
     & [real(kind=dp) :: 0.5_dp, [real(kind=dp) :: global_mua + 0.75_dp * global_sigma, [real(kind &
     & =dp) :: global_mub + 0.75_dp * global_sigma, [real(kind=dp) :: global_muc + 0.75_dp * &
     & global_sigma, [real(kind=dp) :: global_sigma, 0.2_dp]]]]]]]]]]]
  two_fit = fit_two_em(two_initial)
  ! Split component 2 of the two-component fit to initialize three components.
  ! J: split_weight =: 0.5 * 6 { two_fit
  split_weight = 0.5_dp * two_fit(7)
  split_sigma = two_fit(11)
  three_initial = [real(kind=dp) :: two_fit(1), [real(kind=dp) :: two_fit(2), [real(kind=dp) :: &
     & two_fit(3), [real(kind=dp) :: two_fit(4), [real(kind=dp) :: two_fit(5), [real(kind=dp) :: &
     & two_fit(6), [real(kind=dp) :: split_weight, [real(kind=dp) :: two_fit(8) - 0.3_dp * &
     & split_sigma, [real(kind=dp) :: two_fit(9) - 0.3_dp * split_sigma, [real(kind=dp) :: &
     & two_fit(10) - 0.3_dp * split_sigma, [real(kind=dp) :: split_sigma, [real(kind=dp) :: &
     & two_fit(12), [real(kind=dp) :: split_weight, [real(kind=dp) :: two_fit(8) + 0.3_dp * &
     & split_sigma, [real(kind=dp) :: two_fit(9) + 0.3_dp * split_sigma, [real(kind=dp) :: &
     & two_fit(10) + 0.3_dp * split_sigma, [real(kind=dp) :: split_sigma, two_fit(12)]]]]]]]]]]]]] &
     & ]]]]
  three_fit = fit_three_em(three_initial)
  log_likelihoods = [real(kind=dp) :: log_likelihood_one(one_fit), [real(kind=dp) :: &
     & log_likelihood_two(two_fit), log_likelihood_three(three_fit)]]
  ! For k components: k-1 weights and k times (3 means, sigma, rho).
  ! J: parameter_counts =: 5 11 17
  parameter_counts = [5, 11, 17]
  aic = 2 * parameter_counts - 2 * log_likelihoods
  bic = log(real(n, kind=dp)) * parameter_counts - 2 * log_likelihoods
  write (*,"(a)") "dimension and sample size"
  write (*,"(*(i0, 1x))") [dimension_j, n]
  write (*,"(a,1(/,a))") "number of components: 1 2 3", "log likelihood"
  write (*,"(*(g0, 1x))") log_likelihoods
  write (*,"(a)") "AIC"
  write (*,"(*(g0, 1x))") aic
  write (*,"(a)") "BIC"
  write (*,"(*(g0, 1x))") bic
  write (*,"(a)") "components chosen by AIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, aic == minval(aic))))
  write (*,"(a)") "components chosen by BIC"
  write (*,"(i0)") sum((1 + j_iota(3)) * (merge(1, 0, bic == minval(bic))))
  write (*,"(a)") "true two-component parameters"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: true_weight, [real(kind=dp) :: 1 - true_weight, &
     & [real(kind=dp) :: true_means1, [real(kind=dp) :: true_sigma1, [real(kind=dp) :: true_rho1, &
     & [real(kind=dp) :: true_means2, [real(kind=dp) :: true_sigma2, true_rho2]]]]]]]
  write (*,"(a)") "fitted two-component parameters"
  write (*,"(*(g0, 1x))") two_fit
end program fit_mixture_eqc_j
