! Generated by xj2f.py 0.1.0 from mixture.ijs
module mixture_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: mean

contains

pure function mean(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(y) / size(y, 1)
end function mean

end module mixture_j_mod

program mixture_j
  use mixture_j_mod, only: mean
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer :: n, mu1, mu2
  real(kind=dp) :: p, q, sd1, sd2, emp_mean, emp_m2, emp_m3, emp_m4, emp_sd, emp_skew, emp_excess, &
     & theory_mean, raw2, raw3, raw4, theory_m2, theory_m3, theory_m4, theory_sd, theory_skew, &
     & theory_excess
  real(kind=dp), allocatable :: u1(:), u2(:), z1(:), u3(:), u4(:), z2(:), x1(:), x2(:), x(:), &
     & centered(:)
  logical, allocatable :: component1(:)
  real(kind=dp), allocatable :: j_random_1(:)
  ! Simulate a two-component normal mixture and compare its moments with theory.
  ! J: n =: 200000
  n = 200000
  ! Mixture parameters: component 1 has probability p.
  ! J: p =: 0.35
  p = 0.35_dp
  q = 1 - p
  mu1 = -1
  sd1 = 0.8_dp
  mu2 = 2
  sd2 = 1.3_dp
  ! Generate two independent standard normal samples by Box-Muller.
  ! J: u1 =: 1e_12 >. ? n $ 0
  allocate(u1(n), u2(n))
  call random_number(u1)
  u1 = max(1e-12_dp, u1)
  call random_number(u2)
  z1 = sqrt(-2 * log(u1)) * cos(2 * acos(-1.0_dp) * u2)
  allocate(u3(n), u4(n))
  call random_number(u3)
  u3 = max(1e-12_dp, u3)
  call random_number(u4)
  z2 = sqrt(-2 * log(u3)) * cos(2 * acos(-1.0_dp) * u4)
  ! Select a component independently for each observation.
  ! J: component1 =: (? n $ 0) < p
  allocate(j_random_1(n))
  call random_number(j_random_1)
  component1 = j_random_1 < p
  x1 = mu1 + sd1 * z1
  x2 = mu2 + sd2 * z2
  x = merge(1, 0, component1) * x1 + (1 - merge(1, 0, component1)) * x2
  ! Empirical central moments and standardized statistics.
  ! J: emp_mean =: mean x
  emp_mean = mean(x)
  centered = x - emp_mean
  emp_m2 = mean(centered**2)
  emp_m3 = mean(centered**3)
  emp_m4 = mean(centered**4)
  emp_sd = sqrt(emp_m2)
  emp_skew = emp_m3 / (emp_sd**3)
  emp_excess = emp_m4 / (emp_m2**2) - 3
  ! Raw moments of the mixture.  For N(mu,sd^2),
  ! E(X^2)=mu^2+sd^2, E(X^3)=mu^3+3*mu*sd^2,
  ! and E(X^4)=mu^4+6*mu^2*sd^2+3*sd^4.
  ! J: theory_mean =: (p * mu1) + q * mu2
  theory_mean = p * mu1 + q * mu2
  raw2 = p * (mu1**2 + sd1**2) + q * (mu2**2 + sd2**2)
  raw3 = p * (mu1**3 + 3 * mu1 * sd1**2) + q * (mu2**3 + 3 * mu2 * sd2**2)
  raw4 = p * (mu1**4 + 6 * mu1**2 * sd1**2 + 3 * sd1**4) + q * (mu2**4 + 6 * mu2**2 * sd2**2 + 3 * &
     & sd2**4)
  theory_m2 = raw2 - theory_mean**2
  theory_m3 = raw3 - 3 * theory_mean * raw2 + 2 * theory_mean**3
  theory_m4 = raw4 - 4 * theory_mean * raw3 + 6 * theory_mean**2 * raw2 - 3 * theory_mean**4
  theory_sd = sqrt(theory_m2)
  theory_skew = theory_m3 / (theory_sd**3)
  theory_excess = theory_m4 / (theory_m2**2) - 3
  write (*,"(a)") "number of simulations"
  write (*,"(i0)") n
  write (*,"(a)") "mean: empirical theoretical difference"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: emp_mean, [real(kind=dp) :: theory_mean, emp_mean - &
     & theory_mean]]
  write (*,"(a)") "standard deviation: empirical theoretical difference"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: emp_sd, [real(kind=dp) :: theory_sd, emp_sd - &
     & theory_sd]]
  write (*,"(a)") "skewness: empirical theoretical difference"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: emp_skew, [real(kind=dp) :: theory_skew, emp_skew - &
     & theory_skew]]
  write (*,"(a)") "excess kurtosis: empirical theoretical difference"
  write (*,"(*(g0, 1x))") [real(kind=dp) :: emp_excess, [real(kind=dp) :: theory_excess, &
     & emp_excess - theory_excess]]
end program mixture_j
