! Generated by xj2f.py 0.1.0 from normal.ijs
! Simulate standard normal variates with the Box-Muller transform.

module normal_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: mean

contains

pure function mean(y) result(j_result)
  real(kind=dp), intent(in) :: y(:)
  real(kind=dp) :: j_result
  j_result = sum(y) / size(y, 1)
end function mean

end module normal_j_mod

program normal_j
  use normal_j_mod, only: mean
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  integer :: n
  real(kind=dp), allocatable :: u1_raw(:), u1(:), u2(:), radius(:), angle(:), z(:)
  n = 100000
  ! Independent uniform variates in [0,1).  Replacing an exact zero avoids log(0).
  ! J: u1_raw =: ? n $ 0
  allocate(u1_raw(n))
  call random_number(u1_raw)
  u1 = max(1e-12_dp, u1_raw)
  allocate(u2(n))
  call random_number(u2)
  radius = sqrt(-2 * log(u1))
  angle = 2 * acos(-1.0_dp) * u2
  z = radius * cos(angle)
  write (*,"(a)") "number of simulated standard normal variates"
  write (*,"(i0)") n
  write (*,"(a)") "first raw moment (theoretical value 0)"
  write (*,"(g0)") mean(z)
  write (*,"(a)") "second raw moment (theoretical value 1)"
  write (*,"(g0)") mean(z**2)
  write (*,"(a)") "third raw moment (theoretical value 0)"
  write (*,"(g0)") mean(z**3)
  write (*,"(a)") "fourth raw moment (theoretical value 3)"
  write (*,"(g0)") mean(z**4)
end program normal_j
