! Generated by xj2f.py 0.1.0 from price_return_stats_annual.ijs
! Read adjusted prices, compute log returns, and summarize them by year.

module price_return_stats_annual_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: j_read_numeric_csv, j_read_price_years

contains

subroutine j_read_numeric_csv(filename, symbols, values)
  character(len=*), intent(in) :: filename
  character(len=:), allocatable, intent(out) :: symbols(:)
  real(kind=dp), allocatable, intent(out) :: values(:,:)
  character(len=8192) :: line, numeric_line
  character(len=32) :: date_field
  integer :: column, column_count, comma, input_unit, io_status, line_length, row, row_count, start
  open(newunit=input_unit, file=filename, status="old", action="read", iostat=io_status)
  if (io_status /= 0) error stop "cannot open numeric CSV file"
  read(input_unit, "(a)", iostat=io_status) line
  if (io_status /= 0) error stop "numeric CSV file has no header"
  line_length = len_trim(line)
  column_count = 0
  do column = 1, line_length
    if (line(column:column) == ",") column_count = column_count + 1
  end do
  if (column_count < 1) error stop "numeric CSV needs data columns"
  allocate(character(len=32) :: symbols(column_count))
  start = index(line(:line_length), ",") + 1
  do column = 1, column_count
    comma = index(line(start:line_length), ",")
    if (comma == 0) then
      symbols(column) = adjustl(line(start:line_length))
    else
      symbols(column) = adjustl(line(start:start + comma - 2))
      start = start + comma
    end if
  end do
  row_count = 0
  do
    read(input_unit, "(a)", iostat=io_status) line
    if (io_status < 0) exit
    if (io_status > 0) error stop "error reading numeric CSV file"
    if (len_trim(line) > 0) row_count = row_count + 1
  end do
  if (row_count < 2) error stop "numeric CSV needs two data rows"
  rewind(input_unit)
  read(input_unit, "(a)") line
  allocate(values(row_count, column_count))
  row = 0
  do
    read(input_unit, "(a)", iostat=io_status) line
    if (io_status < 0) exit
    if (io_status > 0) error stop "error reading numeric CSV file"
    if (len_trim(line) == 0) cycle
    row = row + 1
    numeric_line = line
    do column = 1, len_trim(numeric_line)
      if (numeric_line(column:column) == ",") numeric_line(column:column) = " "
    end do
    read(numeric_line, *, iostat=io_status) date_field, values(row, :)
    if (io_status /= 0) error stop "invalid numeric CSV data row"
  end do
  close(input_unit)
end subroutine j_read_numeric_csv

subroutine j_read_price_years(filename, expected_rows, years)
  character(len=*), intent(in) :: filename
  integer, intent(in) :: expected_rows
  integer, allocatable, intent(out) :: years(:)
  character(len=8192) :: line
  integer :: input_unit, io_status, row
  open(newunit=input_unit, file=filename, status="old", action="read", iostat=io_status)
  if (io_status /= 0) error stop "cannot open numeric CSV file"
  read(input_unit, "(a)", iostat=io_status) line
  if (io_status /= 0) error stop "numeric CSV file has no header"
  allocate(years(expected_rows))
  row = 0
  do
    read(input_unit, "(a)", iostat=io_status) line
    if (io_status < 0) exit
    if (io_status > 0) error stop "error reading numeric CSV file"
    if (len_trim(line) == 0) cycle
    row = row + 1
    if (row > expected_rows) error stop "CSV row count changed"
    read(line(1:4), *, iostat=io_status) years(row)
    if (io_status /= 0) error stop "invalid year in CSV date"
  end do
  close(input_unit)
  if (row /= expected_rows) error stop "CSV row count changed"
end subroutine j_read_price_years

end module price_return_stats_annual_j_mod

program price_return_stats_annual_j
  use price_return_stats_annual_j_mod, only: j_read_numeric_csv, j_read_price_years
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  character(len=:), allocatable :: symbols(:)
  real(kind=dp), allocatable :: annual_mean(:), annual_volatility(:), centered(:,:), &
     & correlation(:,:), daily_covariance(:,:), daily_maximum(:), daily_mean(:), daily_minimum(:), &
     & daily_volatility(:), log_prices(:,:), prices(:,:), returns(:,:), selected_returns(:,:)
  integer, allocatable :: price_years(:), return_years(:), years(:)
  integer, parameter :: trading_days = 252
  integer :: asset, asset_count, observation_count, return_row, selected_row, year_count, year_index
  call j_read_numeric_csv("asset_class_etf_prices.csv", symbols, prices)
  call j_read_price_years("asset_class_etf_prices.csv", size(prices, 1), price_years)
  log_prices = log(prices)
  returns = log_prices(2:, :) - log_prices(:size(log_prices, 1) - 1, :)
  return_years = price_years(2:)
  asset_count = size(returns, 2)
  allocate(years(size(return_years)))
  year_count = 0
  do return_row = 1, size(return_years)
    if (return_row == 1) then
      year_count = 1
      years(year_count) = return_years(return_row)
    else if (return_years(return_row) /= return_years(return_row - 1)) then
      year_count = year_count + 1
      years(year_count) = return_years(return_row)
    end if
  end do

  write (*,"(a,2(/,a))") "price file", "asset_class_etf_prices.csv", "assets"
  write (*,"(*(a,1x))") (trim(symbols(asset)), asset = 1, asset_count)
  write (*,"(a)") "price rows and return rows"
  write (*,"(2(i0,1x))") size(prices, 1), size(returns, 1)

  do year_index = 1, year_count
    observation_count = count(return_years == years(year_index))
    if (observation_count < 2) error stop "annual return statistics require two observations"
    if (allocated(selected_returns)) deallocate(selected_returns)
    allocate(selected_returns(observation_count, asset_count))
    selected_row = 0
    do return_row = 1, size(returns, 1)
      if (return_years(return_row) == years(year_index)) then
        selected_row = selected_row + 1
        selected_returns(selected_row, :) = returns(return_row, :)
      end if
    end do
    daily_mean = sum(selected_returns, dim=1) / observation_count
    centered = selected_returns - spread(daily_mean, dim=1, ncopies=observation_count)
    daily_covariance = matmul(transpose(centered), centered) / (observation_count - 1)
    daily_volatility = sqrt(j_diagonal(daily_covariance))
    annual_mean = trading_days * daily_mean
    annual_volatility = sqrt(real(trading_days, kind=dp)) * daily_volatility
    daily_minimum = minval(selected_returns, dim=1)
    daily_maximum = maxval(selected_returns, dim=1)
    correlation = daily_covariance / &
      (spread(daily_volatility, dim=2, ncopies=asset_count) * &
       spread(daily_volatility, dim=1, ncopies=asset_count))

    write (*,"(a)") "year and return observations"
    write (*,"(2(i0,1x))") years(year_index), observation_count
    write (*,"(a,i0,a)") "return statistics (annualized using ", trading_days, " trading days)"
    write (*,"(a26,*(1x,a13))") "statistic", (trim(symbols(asset)), asset = 1, asset_count)
    write (*,"(a26,*(1x,f13.6))") "annualized mean log return", annual_mean
    write (*,"(a26,*(1x,f13.6))") "annualized volatility", annual_volatility
    write (*,"(a26,*(1x,f13.6))") "minimum daily log return", daily_minimum
    write (*,"(a26,*(1x,f13.6))") "maximum daily log return", daily_maximum
    write (*,"(a)") "correlation matrix of daily log returns"
    write (*,"(a8,*(1x,a13))") "symbol", (trim(symbols(asset)), asset = 1, asset_count)
    do asset = 1, asset_count
      write (*,"(a8,*(1x,f13.6))") trim(symbols(asset)), correlation(asset, :)
    end do
  end do

contains

pure function j_diagonal(matrix) result(values)
  real(kind=dp), intent(in) :: matrix(:,:)
  real(kind=dp), allocatable :: values(:)
  integer :: diagonal_index, diagonal_size
  diagonal_size = min(size(matrix, 1), size(matrix, 2))
  allocate(values(diagonal_size))
  do diagonal_index = 1, diagonal_size
    values(diagonal_index) = matrix(diagonal_index, diagonal_index)
  end do
end function j_diagonal

end program price_return_stats_annual_j
