! Generated by xj2f.py 0.1.0 from primes.ijs
! Return 1 if y is prime, 0 otherwise

module primes_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: isprime, j_iota

contains

pure elemental function isprime(y) result(j_result)
  integer, intent(in) :: y
  logical :: j_result
  integer :: limit
  integer, allocatable :: divisors(:)
  if (y < 2) then
    j_result = .false.
  else if (y == 2) then
    j_result = .true.
  else
    limit = floor(sqrt(real(y, kind=dp)))
    divisors = 2 + j_iota(limit - 1)
    j_result = .not. any(0 == modulo(y, divisors))
  end if
end function isprime

pure function j_iota(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:)
  integer :: value_index
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n))
  do value_index = 1, n
    values(value_index) = value_index - 1
  end do
end function j_iota

end module primes_j_mod

program primes_j
  use primes_j_mod, only: isprime, j_iota
  implicit none
  integer, allocatable :: nums(:)
  nums = 2 + j_iota(19)
  write (*,"(*(i0, 1x))") pack(nums, isprime(nums))
end program primes_j
