! Generated by xj2f.py 0.1.0 from pythag.ijs
! List Pythagorean triples with hypotenuse <= y

module pythag_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: triples

contains

pure function triples(y) result(j_result)
  integer, intent(in) :: y
  integer, allocatable :: j_result(:,:)
  integer, allocatable :: result_j(:,:)
  integer :: c, b, a
  allocate(result_j(0, 3))
  do c = 1, y
    do b = 1, c - 1
      do a = 1, b - 1
        if (a**2 + b**2 == c**2) then
          call j_append_int_row(result_j, [a, b, c])
        end if
      end do
    end do
  end do
  j_result = result_j
end function triples

pure subroutine j_append_int_row(matrix, row)
  integer, allocatable, intent(inout) :: matrix(:,:)
  integer, intent(in) :: row(:)
  integer, allocatable :: grown(:,:)
  integer :: old_rows
  if (size(matrix, 2) /= size(row)) error stop "J row append shape mismatch"
  old_rows = size(matrix, 1)
  allocate(grown(old_rows + 1, size(matrix, 2)))
  if (old_rows > 0) grown(1:old_rows, :) = matrix
  grown(old_rows + 1, :) = row
  call move_alloc(grown, matrix)
end subroutine j_append_int_row

end module pythag_j_mod

program pythag_j
  use pythag_j_mod, only: triples
  implicit none

  write (*,"(3(i0, 1x))") transpose(triples(30))
end program pythag_j
