! Generated by xj2f.py 0.1.0 from pythag_array.ijs
! Array-oriented Pythagorean triples a,b,c with a<b and c<=y.
! 3 : 0 defines a monadic verb whose argument is y.

module pythag_array_j_mod
  use, intrinsic :: iso_fortran_env, only: dp => real64
  implicit none
  private
  public :: triples

contains

pure function triples(y) result(j_result)
  integer, intent(in) :: y
  integer, allocatable :: j_result(:,:)
  integer, allocatable :: ab(:,:), a(:), b(:), sumsq(:), c(:)
  logical, allocatable :: keep(:)
  ! Box 1..y twice, form their catalogue, then open all ordered pairs.
  ! J: ab =. > , { 2 # < 1 + i. y
  ab = j_cartesian_square(y)
  ! {"1 selects zero-based column 0 from every row.
  ! J: a =. 0 {"1 ab
  a = ab(:, 1)
  ! Select column 1 the same way.
  ! J: b =. 1 {"1 ab
  b = ab(:, 2)
  ! Elementwise arithmetic computes a squared-length for every pair.
  ! J: sumsq =. (a * a) + (b * b)
  sumsq = a**2 + b**2
  ! %: is square root and <. is floor.
  ! J: c =. <. %: sumsq
  c = floor(sqrt(real(sumsq, kind=dp)))
  ! *. ANDs the tests for orientation, an integer c, and the bound.
  ! J: keep =. (a < b) *. (sumsq = c * c) *. (c <: y)
  keep = a < b .and. sumsq == c**2 .and. c <= y
  ! ,. adds c as a column; Boolean # keeps rows selected by keep.
  ! J: keep # ab ,. c
  j_result = j_compress_hcat(ab, c, keep)
end function triples

pure function j_cartesian_square(n) result(values)
  integer, intent(in) :: n
  integer, allocatable :: values(:,:)
  integer :: a, b, row
  if (n < 0) error stop "negative J iota bound"
  allocate(values(n * n, 2))
  row = 0
  do a = 1, n
    do b = 1, n
      row = row + 1
      values(row, :) = [a, b]
    end do
  end do
end function j_cartesian_square

pure function j_compress_hcat(matrix, column, row_selector) result(values)
  integer, intent(in) :: matrix(:,:), column(:)
  logical, intent(in) :: row_selector(:)
  integer, allocatable :: values(:,:)
  integer :: source_row, target_row
  if (size(matrix, 1) /= size(column) .or. &
      size(column) /= size(row_selector)) error stop &
    "J compress shape mismatch"
  allocate(values(count(row_selector), size(matrix, 2) + 1))
  target_row = 0
  do source_row = 1, size(row_selector)
    if (row_selector(source_row)) then
      target_row = target_row + 1
      values(target_row, :) = [matrix(source_row, :), column(source_row)]
    end if
  end do
end function j_compress_hcat

end module pythag_array_j_mod

program pythag_array_j
  use pythag_array_j_mod, only: triples
  implicit none

  ! Print triples with hypotenuse at most 30.
  ! J: echo triples 30
  write (*,"(3(i0, 1x))") transpose(triples(30))
end program pythag_array_j
